<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# import numpy as np
# import pandas as pd
# a = np.array([[1,2,3], [5,6,7]], dtype = int)
# a = pd.DataFrame(a,columns=['a','b','c']).to_csv('sample.csv')

# loading csv file 

In [27]:
import numpy as np
with open('/content/sample.txt') as f:
    print(f.read())


11 12 13 14
21 22 23 24
31 32 33 34


In [29]:
a = np.loadtxt('/content/sample.txt')
print(a)
print(a.dtype) # default type is float64

[[11. 12. 13. 14.]
 [21. 22. 23. 24.]
 [31. 32. 33. 34.]]
float64


## designate dlimiter

In [33]:
with open('/content/sample.txt') as f:
    print(f.read())
print(np.loadtxt('/content/sample.txt',delimiter=' '))

11 12 13 14
21 22 23 24
31 32 33 34
[[11. 12. 13. 14.]
 [21. 22. 23. 24.]
 [31. 32. 33. 34.]]


designate data type

In [37]:
print(np.loadtxt('/content/sample.txt', delimiter=' ', dtype='int64'))

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


## Designate reading columns and row

In [38]:
with open('/content/sample.csv') as f:
    print(f.read())

,a,b,c
0,1,2,3
1,5,6,7



### using skiprows and usecols

In [40]:
a = np.loadtxt('/content/sample.csv', delimiter=',', dtype=int,skiprows=1, usecols=[1,2,3])
print(a)

[[1 2 3]
 [5 6 7]]


まあ pandasを使ったほうが良いんだけどね

In [44]:
a = np.arange(6).reshape((2,3))
print(a)

[[0 1 2]
 [3 4 5]]


In [45]:
np.savetxt('/content/np_savetxt_5e.txt', a, fmt='%.5e')

In [46]:
np.savetxt('/content/np_savetxt.csv', a, delimiter=',', fmt='%d')