<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_dataprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sum, average, max, min

In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a.shape)
print(a)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
print(np.sum(a))

66


In [3]:
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

[12 15 18 21]
[ 6 22 38]


In [4]:
print(a.sum())
print(a.sum(axis = 0))
print(a.sum(axis = 1))

66
[12 15 18 21]
[ 6 22 38]


In [5]:
print(np.mean(a))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [6]:
print(np.min(a))
print(np.min(a, axis = 0))
print(a.max())
print(a.max(axis = 1))

0
[0 1 2 3]
11
[ 3  7 11]


In [7]:
b = np.arange(24).reshape(2,3,4)
print(b.shape)
print(b)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
print(b.sum(axis = 0))
print(b.sum(axis = 1))


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]


In [9]:
print(b.sum(axis = 2))

[[ 6 22 38]
 [54 70 86]]


original : 2 x 3 x 4
<br>axis = 0 : _ x 3 x 4 -> 3 x 4
<br>axis = 1 : 2 x _ x 4 -> 2 x 4
<br>axis = 2 : 2 x 3 x _ -> 2 x 3

In [10]:
# sum(axis = 0)
print(b[0, :, :] + b[1, :, :])

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [11]:
# sum(axis = 1)
print(b[:, 0, :] + b[:, 1, :] + b[:, 2, :])

[[12 15 18 21]
 [48 51 54 57]]


In [12]:
# sum(axis = 2)
print(b[:,:,0] + b[:,:,1] + b[:,:,2] + b[:,:,3])

[[ 6 22 38]
 [54 70 86]]


## set multiple value in tuple to axis...
original : 2 x 3 x 4
<br>axis = (0,1) : _ x _ x 4 -> 4
<br>axis = (0,2) : _ x 3 x _ -> 3
<br>axis = (1,2) : 2 x _ x _ -> 2

In [14]:
print(b)
print(b.sum(axis = (0,1)))
print(b.sum(axis = (0, 2)))
print(b.sum(axis = (1,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[60 66 72 78]
[ 60  92 124]
[ 66 210]


# np.clip
np.clip(ndarray, min, max) -> convert min ~ max values only.

In [15]:
import numpy as np
a = np.arange(10)
print(a)
print(np.clip(a, 2, 7))

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 7 7]


## Want to specify only one of then, Use 'None'

In [16]:
print(np.clip(a, None, 7))
print(np.clip(a, 2, None))

[0 1 2 3 4 5 6 7 7 7]
[2 2 2 3 4 5 6 7 8 9]


In [17]:
a_clip = np.clip(a, 2, 7)
print(a_clip)
print(a)

[2 2 2 3 4 5 6 7 7 7]
[0 1 2 3 4 5 6 7 8 9]


### ndarry.clip()

In [19]:
print(a.clip(2,7))
print(a.clip(None, 7))
print(a.clip(2, None))

[2 2 2 3 4 5 6 7 7 7]
[0 1 2 3 4 5 6 7 7 7]
[2 2 2 3 4 5 6 7 8 9]


In [20]:
print(a.clip(2))
print(a.clip(min = 2))
print(a.clip(max = 7))

[2 2 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 7 7]


# Normalization and standardization

## Normalization Min 0, Max 1
$ x^{'}=\frac{x-min(x)}{max(x) - min(x)}$


## Normalization and standardization ave 0, var 1
$ x^{'}= \frac{x-μ}{σ} $

## Standard deviation of the population.
$ σ^{2}=\frac{1}{n}\sum_{i=1}^{n}(x_i - μ)^2 $

## Sample standard deviation
$u^{2}=\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \overline{x})^2$

## Library that do Normalization and Standardization

## Scipy
### using scipy.stats.zscore()

In [21]:
import scipy.stats
l = [0,1,2,3,4]
print(l)
print(scipy.stats.zscore(l))
print(type(scipy.stats.zscore(l)))

[0, 1, 2, 3, 4]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
<class 'numpy.ndarray'>


### if you designate argument 'ddof = 0', divide 'n'. But 'ddof = 1' divide 'n-1'.

In [22]:
print(scipy.stats.zscore(l, ddof = 1))

[-1.26491106 -0.63245553  0.          0.63245553  1.26491106]


In [24]:
l_2d = [[0,1,2], [3,4,5], [6,7,8]]
print(l_2d)
print(scipy.stats.zscore(l_2d))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [25]:
print(scipy.stats.zscore(l_2d, ddof = 1))

[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [26]:
print(scipy.stats.zscore(l_2d, axis = 1))
print(scipy.stats.zscore(l_2d, axis = 1, ddof = 1))

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [27]:
print(scipy.stats.zscore(l_2d, axis = None))
print(scipy.stats.zscore(l_2d, axis = None, ddof = 1))

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
[[-1.46059349 -1.09544512 -0.73029674]
 [-0.36514837  0.          0.36514837]
 [ 0.73029674  1.09544512  1.46059349]]


## scikit-learn
## sklearn.preprocessing module

In [28]:
from sklearn import preprocessing
l = [0,1,2,3,4]
print(l)
l_2d = [[0,1,2], [3,4,5], [6,7,8]]
print(l_2d)

[0, 1, 2, 3, 4]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### Min-MaxNormalization
use 'MinMaxScaler'

and use fit_transform()

In [29]:
mm = preprocessing.MinMaxScaler()
l_2d_min_max = mm.fit_transform(l_2d)
print(l_2d_min_max)
print(type(l_2d_min_max))

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
<class 'numpy.ndarray'>


### can use minmax_scale() function

In [30]:
print(preprocessing.minmax_scale(l))
print(preprocessing.minmax_scale(l_2d))
print(preprocessing.minmax_scale(l_2d, axis = 1))

[0.   0.25 0.5  0.75 1.  ]
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


### Standardization ave 0, var 1 using 'StandardScaler' or 'scale'
#### and fit_transform(l_2d)

In [31]:
ss = preprocessing.StandardScaler()
l_2d_standardization = ss.fit_transform(l_2d)
print(l_2d_standardization)
print(type(l_2d_standardization))
print(preprocessing.scale(l))
print(preprocessing.scale(l_2d))
print(preprocessing.scale(l_2d, axis = 1))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
<class 'numpy.ndarray'>
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


## Normalization and Standardization Python's "list"
min(), max(), module.statistics, 
<br> use pprintf for easy visualizing
<br>
statistics.stdev() -> divide (n-1) and statistics.pstdev() -> divide n

In [32]:
import statistics
import pprint
l = [0,1,2,3,4]
print(l)
def min_max(l):
    l_min = min(l)
    l_max = max(l)
    return [(i - l_min) / (l_max - l_min) for i in l]
print(min_max(l))

[0, 1, 2, 3, 4]
[0.0, 0.25, 0.5, 0.75, 1.0]


In [33]:
def standardization(l):
    l_mean = statistics.mean(l)
    l_stdev = statistics.stdev(l)
    return [(i-l_mean) / l_stdev for i in l]
pprint.pprint(standardization(l))

[-1.2649110640673518,
 -0.6324555320336759,
 0.0,
 0.6324555320336759,
 1.2649110640673518]


In [35]:
def standardization_p(l):
    l_mean = statistics.mean(l)
    l_pstdev = statistics.pstdev(l)
    return [(i-l_mean)/l_pstdev for i in l]
pprint.pprint(standardization_p(l))

[-1.414213562373095,
 -0.7071067811865475,
 0.0,
 0.7071067811865475,
 1.414213562373095]


## two dimension, ... NumPy ...

In [37]:
l_2d = [[0,1,2], [3,4,5], [6,7,8]]
print(l_2d)
pprint.pprint([min_max(l_1d) for l_1d in l_2d], width = 40)
pprint.pprint([standardization(l_1d) for l_1d in l_2d], width = 40)
pprint.pprint([standardization_p(l_1d) for l_1d in l_2d])

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0.0, 0.5, 1.0],
 [0.0, 0.5, 1.0],
 [0.0, 0.5, 1.0]]
[[-1.0, 0.0, 1.0],
 [-1.0, 0.0, 1.0],
 [-1.0, 0.0, 1.0]]
[[-1.224744871391589, 0.0, 1.224744871391589],
 [-1.224744871391589, 0.0, 1.224744871391589],
 [-1.224744871391589, 0.0, 1.224744871391589]]


In [38]:
l_2d_min_max_col = list(zip(*[min_max(l_1d) for l_1d in list(zip(*l_2d))]))
pprint.pprint(l_2d_min_max_col, width = 40)
l_2d_standardization_col = list(zip(*[standardization(l_1d) for l_1d in list(zip(*l_2d))]))
pprint.pprint(l_2d_standardization_col, width = 40)
l_2d_standardization_p_col = list(zip(*[standardization_p(l_1d) for l_1d in list(zip(*l_2d))]))
pprint.pprint(l_2d_standardization_p_col)

[(0.0, 0.0, 0.0),
 (0.5, 0.5, 0.5),
 (1.0, 1.0, 1.0)]
[(-1.0, -1.0, -1.0),
 (0.0, 0.0, 0.0),
 (1.0, 1.0, 1.0)]
[(-1.2247448713915892, -1.2247448713915892, -1.2247448713915892),
 (0.0, 0.0, 0.0),
 (1.2247448713915892, 1.2247448713915892, 1.2247448713915892)]


## NumPy 's ndarray's Nor, Sta

### ndarray.std() -> ddof = 0, ddof = 1

In [40]:
import numpy as np
import scipy.stats
from sklearn import preprocessing
a = np.array([0,1,2,3,4])
print(a)
print((a - a.min()) / (a.max() - a.min()))
print((a - a.mean()) / a.std())
print((a - a.mean()) / a.std(ddof = 1))

[0 1 2 3 4]
[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.26491106 -0.63245553  0.          0.63245553  1.26491106]


### keep dimension using 'keepdims = True'

In [41]:
a_2d = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(a_2d)
def min_max(x, axis = None):
    x_min = x.min(axis = axis, keepdims = True)
    x_max = x.max(axis = axis, keepdims = True)
    return (x - x_min) / (x_max - x_min)
print(min_max(a_2d))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [42]:
print(min_max(a_2d, axis = 0))
print(min_max(a_2d, axis = 1))
print(min_max(a))

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
[0.   0.25 0.5  0.75 1.  ]


In [44]:
def standardization(x, axis = None, ddof = 0):
    x_mean = x.mean(axis = axis, keepdims = True)
    x_std = x.std(axis = axis, keepdims = True, ddof = ddof)
    return (x-x_mean)/x_std
print(standardization(a_2d))
print(standardization(a_2d, ddof = 1))
print(standardization(a_2d, axis = 0))
print(standardization(a_2d, axis = 0,ddof = 1))
print(standardization(a))
print(standardization(a, ddof = 1))

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
[[-1.46059349 -1.09544512 -0.73029674]
 [-0.36514837  0.          0.36514837]
 [ 0.73029674  1.09544512  1.46059349]]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.26491106 -0.63245553  0.          0.63245553  1.26491106]


## Scipy -> scipy.stats.zscore(a)


In [46]:
print(scipy.stats.zscore(a))
print(scipy.stats.zscore(a_2d))
print(scipy.stats.zscore(a_2d, axis = None, ddof = 1))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
[[-1.46059349 -1.09544512 -0.73029674]
 [-0.36514837  0.          0.36514837]
 [ 0.73029674  1.09544512  1.46059349]]


## if you use sklearn.preprocessing, astype() int to float

In [50]:
mm = preprocessing.MinMaxScaler()
print(mm.fit_transform(a_2d.astype(float)))
print(preprocessing.minmax_scale(a.astype(float)))
print(preprocessing.minmax_scale(a_2d.astype(float), axis = 1))
ss = preprocessing.StandardScaler()
print(ss.fit_transform(a_2d.astype(float)))
print(preprocessing.scale(a.astype(float)))
print(preprocessing.scale(a_2d.astype(float), axis = 1))

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
[0.   0.25 0.5  0.75 1.  ]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


## Use Pandas
### pandas.DataFrame, pandas.Series 's Normalization and Standardization

In [51]:
import pandas as pd
import scipy.stats
from sklearn import preprocessing 
df = pd.DataFrame([[0,1,2],[3,4,5],[6,7,8]], columns = ['col1', 'col2', 'col3'], index = ['a', 'b', 'c'])
print(df)
print((df - df.min()) / (df.max() - df.min()))
print(((df.T - df.T.min()) / (df.T.max() - df.T.min())).T)
print((df - df.values.min()) / (df.values.max() - df.values.min()))

   col1  col2  col3
a     0     1     2
b     3     4     5
c     6     7     8
   col1  col2  col3
a   0.0   0.0   0.0
b   0.5   0.5   0.5
c   1.0   1.0   1.0
   col1  col2  col3
a   0.0   0.5   1.0
b   0.0   0.5   1.0
c   0.0   0.5   1.0
    col1   col2   col3
a  0.000  0.125  0.250
b  0.375  0.500  0.625
c  0.750  0.875  1.000


### Next ave 0, var 1 standardization, normalization

In [54]:
print((df - df.mean()) / df.std())
print((df - df.mean()) / df.std(ddof = 0))
print(((df.T - df.T.mean()) / df.T.std()).T)
print(((df.T - df.T.mean()) / df.T.std(ddof = 0)).T)

# If you use .values, this is 'ndarray'... That is std(ddof = 0) defalut. !!

print((df - df.values.mean()) / df.values.std())
print((df - df.values.mean()) / df.values.std(ddof = 1))

   col1  col2  col3
a  -1.0  -1.0  -1.0
b   0.0   0.0   0.0
c   1.0   1.0   1.0
       col1      col2      col3
a -1.224745 -1.224745 -1.224745
b  0.000000  0.000000  0.000000
c  1.224745  1.224745  1.224745
   col1  col2  col3
a  -1.0   0.0   1.0
b  -1.0   0.0   1.0
c  -1.0   0.0   1.0
       col1  col2      col3
a -1.224745   0.0  1.224745
b -1.224745   0.0  1.224745
c -1.224745   0.0  1.224745
       col1      col2      col3
a -1.549193 -1.161895 -0.774597
b -0.387298  0.000000  0.387298
c  0.774597  1.161895  1.549193
       col1      col2      col3
a -1.460593 -1.095445 -0.730297
b -0.365148  0.000000  0.365148
c  0.730297  1.095445  1.460593


In [55]:
df_ = df.copy()
s = df_['col1']
df_['col1_min_max'] = (s - s.min()) / (s.max() - s.min())
df_['col1_standardization'] = (s - s.mean()) / s.std()
print(df_)

   col1  col2  col3  col1_min_max  col1_standardization
a     0     1     2           0.0                  -1.0
b     3     4     5           0.5                   0.0
c     6     7     8           1.0                   1.0


## Scipy, scikit-learn ... with pandas.DataFrame

In [56]:
print(scipy.stats.zscore(df))
print(type(scipy.stats.zscore(df)))
print(scipy.stats.zscore(df, axis = None, ddof = 1))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
<class 'numpy.ndarray'>
[[-1.46059349 -1.09544512 -0.73029674]
 [-0.36514837  0.          0.36514837]
 [ 0.73029674  1.09544512  1.46059349]]


### return pandas.DataFrame standarded values....

In [58]:
df_standardization = pd.DataFrame(scipy.stats.zscore(df), index = df.index, columns = df.columns)
print(df_standardization)

       col1      col2      col3
a -1.224745 -1.224745 -1.224745
b  0.000000  0.000000  0.000000
c  1.224745  1.224745  1.224745


In [59]:
df_ = df.copy()
df_['col1_standardization'] = scipy.stats.zscore(df_['col1'])
print(df_)

   col1  col2  col3  col1_standardization
a     0     1     2             -1.224745
b     3     4     5              0.000000
c     6     7     8              1.224745


### Example of sklearn.preprocessing

In [61]:
mm = preprocessing.MinMaxScaler()
print(mm.fit_transform(df))
print(type(mm.fit_transform(df)))
print(preprocessing.minmax_scale(df))
print(type(preprocessing.minmax_scale(df)))


[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
<class 'numpy.ndarray'>
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
<class 'numpy.ndarray'>


In [62]:
df_min_max = pd.DataFrame(mm.fit_transform(df), index = df.index, columns = df.columns)
print(df_min_max)
df_ = df.copy()
s = df_['col1'].astype(float)
df_['col1_min_max'] = preprocessing.minmax_scale(s)
df_['col1_standardization'] = preprocessing.scale(s)
print(df_)

   col1  col2  col3
a   0.0   0.0   0.0
b   0.5   0.5   0.5
c   1.0   1.0   1.0
   col1  col2  col3  col1_min_max  col1_standardization
a     0     1     2           0.0             -1.224745
b     3     4     5           0.5              0.000000
c     6     7     8           1.0              1.224745


# Get Max and Min 's index
## use numpy.argmax()
## numpy.ndarray.argmax()
## numpy.argmin()
## numpy.ndarray.argmin()

In [63]:
import numpy as np
a = np.array([1,100,10])
print(a)


[  1 100  10]


### if you designate np.argmax(ndarray), return max values' index

In [64]:
print(np.argmax(a))

1


In [65]:
a = np.array([1,10,10])
print(a)
print(np.argmax(a))

[ 1 10 10]
1


### two dimension

In [66]:
a_2d = np.array([[20,50,30], [60,40,10]])
print(a_2d)
print(np.argmax(a_2d)) # flatten

[[20 50 30]
 [60 40 10]]
3


### ndarray.flatten() do 2 -> 1

In [67]:
print(a_2d.flatten())
print(np.argmax(a_2d.flatten()))

[20 50 30 60 40 10]
3


### MAXindex in each rows and columns...
can set second arguments axis = ?

In [68]:
print(np.argmax(a_2d, axis = 0))
print(np.max(a_2d, axis = 0))

[1 0 0]
[60 50 30]


In [69]:
print(np.argmax(a_2d, axis = 1))
print(np.max(a_2d, axis = 1))

[1 0]
[50 60]


In [70]:
print(a_2d)

[[20 50 30]
 [60 40 10]]


### ALL MAX INDEX ... use np.unravel_index()
* the first arguments : flattened ndarray's "index"
* the second argumants : original ndarray's "shape"
<br>return tuple's index

In [72]:
idx = np.unravel_index(np.argmax(a_2d), a_2d.shape)
print(idx)

(1, 0)


In [73]:
print(a_2d[idx])
print(np.max(a_2d))

60
60


But this way, if max values are so many, dont find.<br>Insted, use 'np.where()'

### ndarray's argmax() method

In [74]:
a = np.array([1,100,10])
print(a)
print(a.argmax())
print(a.max())

[  1 100  10]
1
100


if many dimension are, designate axis for propose.

In [75]:
a_2d = np.array([[20,50,30], [60,40,10]])
print(a_2d)
print(a_2d.argmax())
print(a_2d.argmax(axis = 0))
print(a_2d.max(axis = 0))
print(a_2d.argmax(axis = 1))
print(a_2d.max(axis = 1))

[[20 50 30]
 [60 40 10]]
3
[1 0 0]
[60 50 30]
[1 0]
[50 60]


In [78]:
print(np.unravel_index(a_2d.argmax(), a_2d.shape))

(1, 0)


## np.argmin(), 

In [79]:
import numpy as np
a = np.array([1,100,10])
print(a)
print(np.argmin(a))
print(a.argmin())
a_2d = np.array([[20, 50, 30], [60,40,10]])
print(a_2d)
print(np.argmin(a_2d))
print(a_2d.argmin())
print(np.argmin(a_2d, axis = 0))
print(a_2d.argmin(axis = 0))
print(np.min(a_2d, axis = 0))
print(a_2d.min(axis = 0))
print(np.argmin(a_2d, axis = 1))
print(np.min(a_2d, axis = 1))
print(a_2d.min(axis = 1))

[  1 100  10]
0
0
[[20 50 30]
 [60 40 10]]
5
5
[0 1 1]
[0 1 1]
[20 40 10]
[20 40 10]
[0 2]
[20 10]
[20 10]


In [80]:
idx = np.unravel_index(np.argmin(a_2d), a_2d.shape)
print(idx)
print(a_2d[idx])
print(np.min(a_2d))
print(np.unravel_index(a_2d.argmin(), a_2d.shape))

(1, 2)
10
10
(1, 2)


## USE np.where()
so smart

In [82]:
a_2d = np.array([[10,20,30], [30,20,10]])
print(a_2d)
print(np.max(a_2d))
print(np.min(a_2d))
print(np.unravel_index(np.argmax(a_2d), a_2d.shape))
print(np.unravel_index(np.argmin(a_2d), a_2d.shape))

# only 1 return .. !?

[[10 20 30]
 [30 20 10]]
30
10
(0, 2)
(0, 0)


use np.where()


In [83]:
print(np.where(a_2d == np.max(a_2d)))
print(list(zip(*np.where(a_2d == np.max(a_2d)))))
print(np.where(a_2d == np.min(a_2d)))
print(list(zip(*np.where(a_2d == np.min(a_2d)))))

(array([0, 1]), array([2, 0]))
[(0, 2), (1, 0)]
(array([0, 1]), array([0, 2]))
[(0, 0), (1, 2)]


# conver One-Hot representation by 'eye' or 'indentity'

## numpy.eye()
make 2 dimension in 1 diagonally aigned and the rest 0.

In [85]:
e = np.eye(4)
print(e)
print(e.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [90]:
e = np.eye(4, M=3, k = 1, dtype = np.int8) # M is columns size, k is 1's start position.
print(e)
print(e.dtype)

[[0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]
int8


In [91]:
i = np.identity(4)
print(i)
print(i.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [92]:
i = np.identity(4, dtype = np.uint8)
print(i)
print(i.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
uint8


In [ ]:
from numpy import eye
return eye(n, dtype = dtype)

## convert one-hot representation

In [95]:
a = [3,0,8,1,9]
a_one_hot = np.identity(10)[a] # index position y = 1, x = 3... y = 2, x = 0...
print(a)
print(a_one_hot)

[3, 0, 8, 1, 9]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [94]:
a = [2,2,0,1,0]
a_one_hot = np.identity(3)[a]
print(a)
print(a_one_hot)

[2, 2, 0, 1, 0]
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


# scroll ndarray 'np.roll'
shift , scroll...

In [97]:
import numpy as np
a = np.arange(10)
print(a)
a_roll = np.roll(a, 3) # 3bit right shift,,, rollllling 
print(a_roll)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[7 8 9 0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


In [98]:
a_roll[0] = 100
print(a_roll)
print(a)
# not view

[100   8   9   0   1   2   3   4   5   6]
[0 1 2 3 4 5 6 7 8 9]


In [99]:
print(np.roll(a, -3))
print(np.roll(a, 12))

[3 4 5 6 7 8 9 0 1 2]
[8 9 0 1 2 3 4 5 6 7]


In [100]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d) # flattened 1 dimension
print(np.roll(a_2d, 2))
print(np.roll(a_2d, 5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[10 11  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 7  8  9 10]
 [11  0  1  2]
 [ 3  4  5  6]]


but designate axis, shift along that axis.

In [101]:
print(np.roll(a_2d, 1, axis = 0))
print(np.roll(a_2d, 2, axis = 1))

[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[ 2  3  0  1]
 [ 6  7  4  5]
 [10 11  8  9]]


by using tuple( ? , ?) ... shit along (?, ?)

In [102]:
print(np.roll(a_2d, (1,2), axis = (0,1)))

[[10 11  8  9]
 [ 2  3  0  1]
 [ 6  7  4  5]]


In [103]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)
print(np.roll(a_3d, 3))
print(np.roll(a_3d, 2, axis = 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[21 22 23  0]
  [ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]]
[[[ 2  3  0  1]
  [ 6  7  4  5]
  [10 11  8  9]]

 [[14 15 12 13]
  [18 19 16 17]
  [22 23 20 21]]]


## image scrolling...

In [ ]:
import numpy as np
from PIL import Image
img = np.array(Image.open('data/src/lena.jpg'))
print(img.shape)
img_scroll = np.roll(img, (50,100), axis = (0,1))
Image.fromarray(img_scroll).save('data/dst/lena_numpy_roll.jpg')

# Matrix Operations ( Inverse matrix, determinant, eigenvalue )


In [104]:
l_2d = [[0,1,2], [3,4,5]]
print(l_2d)
print(type(l_2d))

[[0, 1, 2], [3, 4, 5]]
<class 'list'>


In [105]:
arr = np.array([[0,1,2], [3,4,5]])
print(arr)

[[0 1 2]
 [3 4 5]]


In [106]:
print(type(arr))

<class 'numpy.ndarray'>


In [107]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [108]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


## NumPy Matrix, numpy.matrix, numpy.matrix()

In [109]:
mat = np.matrix([[0,1,2], [3,4,5]])
print(mat)

[[0 1 2]
 [3 4 5]]


In [110]:
print(type(mat))
mat = np.matrix(arr)
print(mat)
print(type(mat))

<class 'numpy.matrix'>
[[0 1 2]
 [3 4 5]]
<class 'numpy.matrix'>


## numpy.matrix is special for '2 dimension'

In [111]:
mat_1d = np.matrix([0,1,2])
print(mat_1d)
print(type(mat_1d))
print(mat_1d.shape)

[[0 1 2]]
<class 'numpy.matrix'>
(1, 3)


### difference both list and ndarray

In [112]:
print(l_2d)
print(l_2d[0][1])
l_2d[0][1] = 100
print(l_2d)

[[0, 1, 2], [3, 4, 5]]
1
[[0, 100, 2], [3, 4, 5]]


In [113]:
print(arr)
print(arr[0,1])
arr[0,1] = 100
print(arr)

[[0 1 2]
 [3 4 5]]
1
[[  0 100   2]
 [  3   4   5]]


## Transposition .. .T difference both list and ndarray

In [114]:
l_2d = [[0,1,2], [3,4,5]]
print(l_2d)
print([list(x) for x in list(zip(*l_2d))])


[[0, 1, 2], [3, 4, 5]]
[[0, 3], [1, 4], [2, 5]]


In [115]:
arr = np.arange(6).reshape((2,3))
print(arr)
print(arr.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


## + and - , if it is list, error. + is list connection, not plus.

In [116]:
l_2d_1 = [[0,1,2], [3,4,5]]
l_2d_2 = [[0,2,4], [6,8,10]]
print(l_2d_1 + l_2d_2)

[[0, 1, 2], [3, 4, 5], [0, 2, 4], [6, 8, 10]]


In [119]:
arr1 = np.arange(6).reshape((2,3))
arr2 = np.arange(0,12,2).reshape((2,3))
print(arr2)
print(arr1 + arr2)
print(arr1 - arr2)

[[ 0  2  4]
 [ 6  8 10]]
[[ 0  3  6]
 [ 9 12 15]]
[[ 0 -1 -2]
 [-3 -4 -5]]


In [120]:
mat1 = np.matrix(arr1)
mat2 = np.matrix(arr2)
print(mat1 + mat2)
print(mat1 - mat2)

[[ 0  3  6]
 [ 9 12 15]]
[[ 0 -1 -2]
 [-3 -4 -5]]


## scolar double list vs ndarray

In [121]:
print(l_2d_1 * 2)
print(arr1 * 2)
print(mat1 * 2)

[[0, 1, 2], [3, 4, 5], [0, 1, 2], [3, 4, 5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  2  4]
 [ 6  8 10]]


In [122]:
print(np.multiply(arr1, arr2))
print(np.multiply(mat1, mat2))
print(arr1 * arr2)

[[ 0  2  8]
 [18 32 50]]
[[ 0  2  8]
 [18 32 50]]
[[ 0  2  8]
 [18 32 50]]


## processional product numpy.dot(), numpy.matmul(). @

In [123]:
arr1 = np.arange(4).reshape((2,2))
print(arr1)
arr2 = np.arange(6).reshape((2,3))
print(np.dot(arr1, arr2))
print(arr1.dot(arr2))
print(np.matmul(arr1,arr2))
print(arr1 @ arr2)

[[0 1]
 [2 3]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]


## in numpy.matrix, can use * !

In [124]:
mat1 = np.matrix(arr1)
mat2 = np.matrix(arr2)
print(np.dot(mat1, mat2))
print(mat1.dot(mat2))
print(np.matmul(mat1, mat2))
print(mat1 @ mat2 )
print(mat1 * mat2)

[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]


## A power ride ** 

In [125]:
arr = np.arange(1,5).reshape(2,2)
print(arr)

[[1 2]
 [3 4]]


In [127]:
print(arr**2)

[[ 1  4]
 [ 9 16]]


In [128]:
mat = np.matrix(arr)
print(mat)
print(mat**2)
print(mat**2 == mat * mat)
print(mat**3 == mat * mat * mat)

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


In [129]:
arr_f = np.array(arr, dtype = float)
print(arr_f **-1)

[[1.         0.5       ]
 [0.33333333 0.25      ]]


### Inverse matrix **-1 to numpy.matrix

In [130]:
print(mat**-1)
print(mat**-2)


[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


## inner product of the vectors
numpy.inner()

In [131]:
v = np.array([0,1,2])
print(v)
print(v.shape)
print(np.inner(v,v))
print(type(np.inner(v,v)))

[0 1 2]
(3,)
5
<class 'numpy.int64'>


In [132]:
print(np.dot(v,v))
print(np.matmul(v,v))
print(v @ v)

5
5
5


In [133]:
arr_row = np.arange(3).reshape(1,3)
print(arr_row)
print(arr_row.shape)
arr_col = np.arange(3).reshape(3,1)
print(arr_col)
print(arr_col.shape)

[[0 1 2]]
(1, 3)
[[0]
 [1]
 [2]]
(3, 1)


In [134]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [135]:
print(v)

[0 1 2]


In [136]:
print(v @ arr)

[15 18 21]


In [137]:
print(arr_row)

[[0 1 2]]


In [138]:
print(arr_row @ arr)

[[15 18 21]]


In [140]:
print(arr @ v) # v -> transformed (3,1) automation

[ 5 14 23]


In [141]:
print(arr @ arr_col)

[[ 5]
 [14]
 [23]]


### Inverse Matrix, numpy.linalg.inv(), **-1, .l attribute

In [142]:
arr = np.array([[2,5], [1,3]])
arr_inv = np.linalg.inv(arr)
print(arr_inv)
mat = np.matrix([[2,5], [1,3]])
mat_inv = np.linalg.inv(mat)
print(mat_inv)

[[ 3. -5.]
 [-1.  2.]]
[[ 3. -5.]
 [-1.  2.]]


In [143]:
mat_inv = mat**-1
print(mat_inv)

[[ 3. -5.]
 [-1.  2.]]


In [144]:
mat_inv = mat.I
print(mat_inv)

[[ 3. -5.]
 [-1.  2.]]


### Original Matrix * Inverse Matrix = Unit Matrix

In [145]:
result = mat * mat.I
print(result)

[[1. 0.]
 [0. 1.]]


### .I has numpy.matrix only

## 擬似逆行列: numpy.linalg.pinv() なんだこれ?
### 逆行列が存在しない（特異行列である）場合

In [147]:
arr_s = np.array([[0,0], [1,3]])
print(arr_s)

[[0 0]
 [1 3]]


if you use np.linalg.inv(arr_s), occur error.

In [148]:
arr_pinv = np.linalg.pinv(arr_s)
print(arr_pinv)

[[0.  0.1]
 [0.  0.3]]


In [149]:
print(arr_s @ arr_inv)
print(np.linalg.pinv(arr_pinv))

[[0. 0.]
 [0. 1.]]
[[0. 0.]
 [1. 3.]]


In [151]:
mat_s = np.mat([[0,0],[1,3]])
print(np.linalg.pinv(mat_s))

[[0.  0.1]
 [0.  0.3]]


## Calculate the matrix formula ... numpy.linalg.det()

In [152]:
arr = np.array([[0,1],[2,3]])
det = np.linalg.det(arr)
print(det)

-2.0


## Eigenvalues and eigenvectors... numpy.linalg.eig()

In [154]:
arr = np.array([[8,1], [4,5]])
w,v = np.linalg.eig(arr)
print(w)

[9. 4.]


In [155]:
print(v)

[[ 0.70710678 -0.24253563]
 [ 0.70710678  0.9701425 ]]


In [156]:
print('value: ', w[0])
print('vector: ', v[:, 0] / v[0,0])

value:  9.0
vector:  [1. 1.]


In [158]:
print(w[np.argmax(w)])
print(v[:, np.argmax(w)])

9.0
[0.70710678 0.70710678]


In [159]:
def get_eigenpairs(arr):
    w, v = np.linalg.eig(arr)
    eigenpairs = []

    for i, val in enumerate(w):
        vec = v[:, i] / np.min(np.abs(v[:, i][v[:, i] != 0]))
        eigenpairs.append((val, vec))

    return eigenpairs

eigenpairs = get_eigenpairs(arr)

for val, vec in eigenpairs:
    print('value: {}, vector: {}'.format(val, vec))
# value: 9.0, vector: [1. 1.]
# value: 4.0, vector: [-1.  4.]

value: 9.0, vector: [1. 1.]
value: 4.0, vector: [-1.  4.]


In [160]:
arr = np.array([[1, 1, 2], [0, 2, -1], [0, 0, 3]])

eigenpairs = get_eigenpairs(arr)

for val, vec in eigenpairs:
    print('value: {}, vector: {}'.format(val, vec))
# value: 1.0, vector: [1. 0. 0.]
# value: 2.0, vector: [1. 1. 0.]
# value: 3.0, vector: [ 1. -2.  2.]

value: 1.0, vector: [1. 0. 0.]
value: 2.0, vector: [1. 1. 0.]
value: 3.0, vector: [ 1. -2.  2.]


In [161]:
arr = np.array([[3, 2], [-2, 3]])

eigenpairs = get_eigenpairs(arr)

for val, vec in eigenpairs:
    print('value: {}, vector: {}'.format(val, vec))
# value: (3+2.0000000000000004j), vector: [0.-1.j 1.+0.j]
# value: (3-2.0000000000000004j), vector: [0.+1.j 1.-0.j]

value: (3+2.0000000000000004j), vector: [0.-1.j 1.+0.j]
value: (3-2.0000000000000004j), vector: [0.+1.j 1.-0.j]
