# What is pytorch
* https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
* numpy の replacement
* maximum flexibility and speed 
* Tensors

## Tensors
* similar to NumPy's ndarrays, and used on a GPU to accelerate

In [1]:
from __future__ import print_function

In [2]:
import torch

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[8.7312e-10, 7.8285e-10, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39]])


In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.3553, 0.3094, 0.6521],
        [0.2916, 0.2376, 0.9243],
        [0.6361, 0.5699, 0.3799],
        [0.1049, 0.5717, 0.8185],
        [0.1617, 0.7389, 0.5463]])


In [6]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1493, -2.0528,  0.2972],
        [ 1.5095, -0.1686, -1.6283],
        [ 0.4666,  0.2774, -0.6822],
        [-0.1033,  0.8514,  0.1146],
        [-1.0455,  0.0105,  0.6034]])


In [10]:
print(x.size())

torch.Size([5, 3])


## operations
* multiple syntaxes for operations
* take a look at the addition operation

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8484, -1.5348,  1.1598],
        [ 1.8245,  0.7618, -1.0230],
        [ 0.7162,  0.5276,  0.1463],
        [-0.0753,  1.4462,  0.6239],
        [-0.4771,  0.5939,  1.5985]])


In [12]:
print(torch.add(x,y))

tensor([[ 0.8484, -1.5348,  1.1598],
        [ 1.8245,  0.7618, -1.0230],
        [ 0.7162,  0.5276,  0.1463],
        [-0.0753,  1.4462,  0.6239],
        [-0.4771,  0.5939,  1.5985]])


In [14]:
# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.8484, -1.5348,  1.1598],
        [ 1.8245,  0.7618, -1.0230],
        [ 0.7162,  0.5276,  0.1463],
        [-0.0753,  1.4462,  0.6239],
        [-0.4771,  0.5939,  1.5985]])


In [16]:
y.add_(x)
print(y)

tensor([[ 0.9977, -3.5876,  1.4570],
        [ 3.3340,  0.5932, -2.6513],
        [ 1.1828,  0.8050, -0.5359],
        [-0.1786,  2.2975,  0.7384],
        [-1.5226,  0.6044,  2.2019]])


In [24]:
r = torch.empty(3,3)
d = torch.empty(2,5)
print(r)
torch.add(x,y,out=r)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([[ 1.1469, -5.6404,  1.7542],
        [ 4.8436,  0.4246, -4.2796],
        [ 1.6494,  1.0824, -1.2181],
        [-0.2819,  3.1489,  0.8530],
        [-2.5681,  0.6149,  2.8053]])

* x.copy_(y), x.t_()

In [25]:
print(x[:,1])

tensor([-2.0528, -0.1686,  0.2774,  0.8514,  0.0105])


* if you resize / reshape tensor, you can use **torch.view**

In [26]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
print(y)

tensor([-1.2148,  2.0330,  0.6045, -0.3537, -0.2840,  0.2998, -0.3996,  0.6928,
        -1.6227,  2.0945,  0.9089,  0.2543, -0.2927,  0.6855,  1.6058, -0.9220])


* if you have a one element tensor, use .item() to get the value as a Python number

In [30]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0281])
-1.0280979871749878


* more information -> https://pytorch.org/docs/stable/torch.html

## Numpy -> Tensor Bridge, Tensor -> Numpy

In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [34]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


* memory view

In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
* any device using the .to method

In [36]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

In [37]:
torch.cuda.is_available()

False

In [38]:
CUDA_VISIBLE

NameError: name 'nvcc' is not defined