<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/Pytorch/LearningPytorch_1_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'1.5.1+cu101'

In [2]:
# 行列
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.randn(2,4)
# 平均0、分散1（標準偏差1）の正規分布（標準正規分布）に従う乱数を返す。

tensor([[ 1.1589, -0.3486,  0.0835,  1.5666],
        [ 0.4683,  1.4804, -0.9162, -1.2267]])

In [8]:
# 層の定義
# 層の重みとバイアスを定義してしまえる
import torch.nn as nn
# 乱数シードの固定
torch.manual_seed(1)
# 全結合層の定義
fc = nn.Linear(3,2) # 入力と出力

In [9]:
# 中身を確認
print(fc.weight)
print(fc.bias)

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)
Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)


In [10]:
# 入力値の定義
# https://www.tensorflow.org/tutorials/customization/basics?hl=ja#%E3%83%86%E3%83%B3%E3%82%BD%E3%83%AB
X = torch.tensor([[1,2,3]], dtype = torch.float32)
# X を 3 個
print(X.shape)
X.dtype

torch.Size([1, 3])


torch.float32

In [11]:
y = fc(X)
y

tensor([[-0.6667,  0.5164]], grad_fn=<AddmmBackward>)

In [12]:
# 非線形変換
# 活性化関数のReLUを試す (0 以下を0に変換しちゃう)
import torch.nn.functional as F
# ReLU
z = F.relu(y)
z

tensor([[0.0000, 0.5164]], grad_fn=<ReluBackward0>)

In [13]:
# 多層化
# 定義を層によってそれぞれ
fc1 = nn.Linear(3,2)
fc2 = nn.Linear(2,1)
X = torch.tensor([[1,2,3]], dtype=torch.float32)
# 一層目
h1 = fc1(X)
z1 = F.relu(h1) # ReLu
# 2層目
u2 = fc2(z1)
u2

tensor([[0.6568]], grad_fn=<AddmmBackward>)

In [30]:
# PyTorchのコスト関数(損失関数)
# 予測した数値と正解の数値の差を定量化したコスト関数
# 回帰 平均二乗誤差 mean_square_error ? // nn.MSELoss
# 多クラス分類 ソフトマックス交差エントロピ誤差 nn.CrossEntropyLoss

import torch
import torch.nn as nn

# MSELoss 平均二乗誤差
x = torch.randn(4)
y = torch.randn(4)
print("x: ", x)
print("y: ", y)
criterion = nn.MSELoss()
loss = criterion(x,y)
print("MSELoss: ", loss)

# CrossEntropyLoss
x = torch.randn(1,4)
y = torch.LongTensor([1]).random_(4)
#print(y)
criterion = nn.CrossEntropyLoss()
loss = criterion(x,y)
print("CrossEntropyLoss: ", loss)

x:  tensor([ 0.8473, -0.1348,  0.6477, -1.6412])
y:  tensor([-0.4636,  0.3857,  1.1993,  1.8805])
MSELoss:  tensor(3.6740)
CrossEntropyLoss:  tensor(1.4954)


In [35]:
# コードの中では
# コスト関数の設定
criterion = nn.CrossEntropyLoss()
# ロスの計算(y: 計算結果, t:正解ラベル)
loss = criterion(x,y)
# 勾配の計算
loss.backward()

TypeError: ignored

In [41]:
# https://start0x00url.net/2018/09/18/pytorch-%E3%81%AE%E5%8B%95%E4%BD%9C%E7%A2%BA%E8%AA%8D%E3%82%92%E3%81%97%E3%81%A6%E3%81%BF%E3%81%9F%EF%BC%88%EF%BC%92%EF%BC%89/
# コードの中では
# コスト関数の設定
x = torch.randn(1,4, requires_grad=True)
y = torch.LongTensor([1]).random_(4)
criterion = nn.CrossEntropyLoss()
# ロスの計算(y: 計算結果, t:正解ラベル)
loss = criterion(x,y)
# 勾配の計算
loss.backward()
print(x.grad)

tensor([[ 0.2096,  0.4552, -0.8727,  0.2080]])


In [42]:
# PyTorchの重みの更新(最適化)
import torch
import torch.optim as optim
# コスト数で導いたロスから、パラメータ(重みとバイアス)の学習をする
# あらかじめ用意されている
# どれかを使う
optimizer = optim.SGD(net.parameters(), lr = 0.1)
optimizer = optim.Adagrad(net.parameters())
optimizer = optim.RMSprop(net.parameters())
optimizer = optim.Adam(net.parameters(), lr = 1e-1, betas=(0.9, 0.99), eps=1e-09)

NameError: ignored

In [49]:
! nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [50]:
!pip install -U torch torchvision

Requirement already up-to-date: torch in /usr/local/lib/python3.6/dist-packages (1.5.1+cu101)
Requirement already up-to-date: torchvision in /usr/local/lib/python3.6/dist-packages (0.6.1+cu101)


In [51]:
torch.cuda.is_available()

False

In [4]:
# GPU を使った計算処理
# PyTorchでGPU使えますかと

# Falseだったけど

# ランタイム更新した

print(torch.cuda.is_available())
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

True


device(type='cuda', index=0)

In [6]:
x = torch.randn(4)
x = x.to(device)
x

tensor([ 0.2064,  0.1789, -0.9341,  0.4532], device='cuda:0')