<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/Pytorch/LearningPytorch_1_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'1.5.1+cu101'

In [2]:
# 行列
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.randn(2,4)
# 平均0、分散1（標準偏差1）の正規分布（標準正規分布）に従う乱数を返す。

tensor([[ 1.1589, -0.3486,  0.0835,  1.5666],
        [ 0.4683,  1.4804, -0.9162, -1.2267]])

In [8]:
# 層の定義
# 層の重みとバイアスを定義してしまえる
import torch.nn as nn
# 乱数シードの固定
torch.manual_seed(1)
# 全結合層の定義
fc = nn.Linear(3,2) # 入力と出力

In [9]:
# 中身を確認
print(fc.weight)
print(fc.bias)

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)
Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)


In [ ]:
# 入力値の定義
# https://www.tensorflow.org/tutorials/customization/basics?hl=ja#%E3%83%86%E3%83%B3%E3%82%BD%E3%83%AB
