<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ConfirmVersion

In [1]:
import numpy as np
print(np.__version__)

1.18.5


#Datacasting

In [2]:
a = np.array([1,2,3], dtype = np.int64)
print(a.dtype)
# or 'i8'

int64


In [5]:
a = np.array([1,2,3], dtype = int)
print(a.dtype)

int64


## Confirm max and min dtypes

In [6]:
ii64 = np.iinfo(np.int64)
print(type(ii64))

<class 'numpy.iinfo'>


In [7]:
print(ii64)

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [8]:
print(ii64.max)
print(ii64.min)
print(ii64.bits)

9223372036854775807
-9223372036854775808
64


In [11]:
print(np.iinfo('i4'))
print(np.iinfo('i2'))
print(np.iinfo('uint64'))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for uint64
---------------------------------------------------------------
min = 0
max = 18446744073709551615
---------------------------------------------------------------



In [12]:
# but ndarray is not iinfo()
a = np.array([1,2,3], dtype = np.int8)
print(type(a))
print(np.iinfo(a))

<class 'numpy.ndarray'>


ValueError: ignored

In [14]:
print(np.iinfo(a.dtype))
print(np.iinfo(a[0]))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



### using np.finfo() to float

In [15]:
fi64 = np.finfo(np.float64)
print(fi64)

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



## array string

In [16]:
a_str = np.array([1,2,3], dtype=str)
print(a_str)
print(a_str.dtype)

['1' '2' '3']
<U1


###<U1 リトルエンディアン

In [17]:
a_str[0] = 'abcde'
print(a_str)

['a' '2' '3']


1 string only.
The way to escape this problem is using dtype='U??'

In [19]:
a_str10 = np.array([1,2,3], dtype='U10')
a_str10[0] = 'abcde'
print(a_str10)

['abcde' '2' '3']


### object型 Pythonobject multi-dataset

In [20]:
a_object = np.array([1,0.1,'one'], dtype = object)
print(a_object)

[1 0.1 'one']


In [21]:
print(type(a_object[0]))
print(type(a_object[1]))

<class 'int'>
<class 'float'>


This can be achieve by using 'list',<br>
but caluculation is different.

In [22]:
l = [1,0.1,'oneONE']
print(a_object * 2)
print(l*2)

[2 0.2 'oneone']
[1, 0.1, 'oneONE', 1, 0.1, 'oneONE']


# data type casting by using astype()

In [25]:
a = np.array([1,2,3])
print(a)
a_float = a.astype(np.float32)
print(a_float)

[1 2 3]
[1. 2. 3.]


In [26]:
a_float = a.astype(float)
print(a_float.dtype)

float64


In [28]:
a_str = a.astype(str)
print(a_str.dtype)

<U21


In [30]:
a_int = a.astype('int32')
print(a_int.dtype)

int32


Points to note when converting(casting) with astype()

In [33]:
a = np.arange(50).reshape((5,10)) / 10 - 2
print(a)

[[-2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1]
 [-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1]
 [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
 [ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]
 [ 2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9]]


In [34]:
a_int = a.astype('int64')
print(a_int)

[[-2 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]]


In [35]:
# using round() is converting numerics to even. 0.5 -> 0
print(np.round(a).astype(int))

[[-2 -2 -2 -2 -2 -2 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  1  1]
 [ 1  1  1  1  1  2  2  2  2  2]
 [ 2  2  2  2  2  2  3  3  3  3]]


In [36]:
# To want to 0.5 -> 1
my_round_int = lambda x:np.round((x*2 + 1)//2)
print(my_round_int(a).astype(int))

[[-2 -2 -2 -2 -2 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  1  1  1]
 [ 1  1  1  1  1  2  2  2  2  2]
 [ 2  2  2  2  2  3  3  3  3  3]]


In [37]:
# implicit conversion
a = np.array([1,2,3])
print((a//1).dtype)
print((a//1.0).dtype)

int64
float64


In [38]:
ones_int16 = np.ones(3, np.int16)
print(ones_int16)
ones_int32 = np.ones(3, np.int32)
print(ones_int32)
print((ones_int16 + ones_int32).dtype)

[1 1 1]
[1 1 1]
int32


# list, array, numpy.ndarray difference

* リスト
* 配列
* 多次元配列

## list

In [39]:
# buildin
l = ['apple',100,0.123]
l_2d = [[0,1,2],[3,4,5],[6,7,8]]

## array
import<br>same dtype only<br>one dimension only

In [40]:
import array
arr_int = array.array('i', [0,1,2])
print(arr_int)
arr_float = array.array('f', [0.0, 0.1, 0.2])
print(arr_float)

array('i', [0, 1, 2])
array('f', [0.0, 0.10000000149011612, 0.20000000298023224])


#numpy.ndarray
import<br>samedtype(but object type is usable)<br>multi dimension<br>matrix calculation<br>so many usings and so fast

In [42]:
import numpy as np
arr = np.array([0,1,2])
arr_2d = np.array([[0,1,2], [3,4,5]])
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [43]:
print(arr_2d[1,1])
print(arr_2d[0,1:])

4
[1 2]


**for each elements**

In [44]:
print(np.sqrt(arr_2d))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]


In [45]:
arr_1 = np.array([[1,2], [3,4]])
arr_2 = np.array([[1,2,3], [4,5,6]])
print(np.dot(arr_1, arr_2))

[[ 9 12 15]
 [19 26 33]]


nd = N - dimensional

# using ndarray can make use of pandas

In [ ]:
import pandas as pd
df = pd.read_csv('data/src/~~', index_col = 0)
df['sex'] = ['Female', 'Male'...]
print(df)
print(df.mean())
print(df.pivot_table(index = 'state', columns = 'sex', aggfunc='mean'))