<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lets sorting by using 'argsort'

In [120]:
import numpy as np
a = np.array([3,4,2,0,1])
print(a)
a_sort = np.sort(a)
print(a_sort)
print(a)

[3 4 2 0 1]
[0 1 2 3 4]
[3 4 2 0 1]


## numpy has not reverse
Instead, use [::-1]

In [121]:
a_sort_reverse = np.sort(a)[::-1]
print(a_sort_reverse)

[4 3 2 1 0]


In [122]:
a_2d = np.array([[20, 3, 100], [1, 200, 30], [300, 10, 2]])
print(a_2d)

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]


In [123]:
a_2d_sort_col = np.sort(a_2d, axis = 0)
a_2d_sort_row = np.sort(a_2d, axis = 1)
print(a_2d_sort_col)
print(a_2d_sort_row)

[[  1   3   2]
 [ 20  10  30]
 [300 200 100]]
[[  3  20 100]
 [  1  30 200]
 [  2  10 300]]


## default axis = -1, last dimension

### if you do decending order, use slice [::-1], [:, ::-1]

In [124]:
a_2d_sort_col_reverse = np.sort(a_2d,axis = 0)[::-1]
print(a_2d_sort_col_reverse)
a_2d_sort_row_reverse = np.sort(a_2d, axis = 1)[:, ::-1]
print(a_2d_sort_row_reverse)

[[300 200 100]
 [ 20  10  30]
 [  1   3   2]]
[[100  20   3]
 [200  30   1]
 [300  10   2]]


In [125]:
print(a_2d)
a_2d.sort()
print(a_2d)
a_2d.sort(axis = 0)
print(a_2d[::-1])

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]
[[  3  20 100]
 [  1  30 200]
 [  2  10 300]]
[[  3  30 300]
 [  2  20 200]
 [  1  10 100]]


# Lets use numpy.argsort() !!!

## return not values but 'sorted index' !!

In [127]:
a_2d = np.array([[20, 3, 100],[1,200,30],[300,10,2]])
print(a_2d)
a_2d_sort_col_index = np.argsort(a_2d, axis = 0)
print(a_2d_sort_col_index)
a_2d_sort_row_index = np.argsort(a_2d)
print(a_2d_sort_row_index)

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]
[[1 0 2]
 [0 2 1]
 [2 1 0]]
[[1 0 2]
 [0 2 1]
 [2 1 0]]


## How to sort by a specifict row or column

In [128]:
print(a_2d)

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]


In [129]:
col_num = 1
print(a_2d[:, col_num])

[  3 200  10]


In [130]:
print(np.argsort(a_2d[:, col_num]))

[0 2 1]


In [131]:
a_2d_sort_col_num = a_2d[np.argsort(a_2d[:, col_num])]
print(a_2d_sort_col_num)

[[ 20   3 100]
 [300  10   2]
 [  1 200  30]]


In [132]:
print(np.argsort(a_2d[:, col_num])[::-1])
a_2d_sort_col_num_reverse = a_2d[np.argsort(a_2d[:, col_num])[::-1]]
print(a_2d_sort_col_num_reverse)

[1 2 0]
[[  1 200  30]
 [300  10   2]
 [ 20   3 100]]


## specifit row

In [137]:
print(a_2d)
row_num = 1
print(a_2d[row_num])

[[ 20   3 100]
 [  1 200  30]
 [300  10   2]]
[  1 200  30]


In [134]:
print(np.argsort(a_2d[row_num]))


[0 2 1]


In [136]:
a_2d_sort_row_num = a_2d[:, np.argsort(a_2d[row_num])]
print(a_2d_sort_row_num)

[[ 20 100   3]
 [  1  30 200]
 [300   2  10]]


In [139]:
print(np.argsort(a_2d[row_num])[::-1])

[1 2 0]


In [140]:
a_2d_sort_row_num_inverse = a_2d[:, np.argsort(a_2d[row_num])[::-1]]
print(a_2d_sort_row_num_inverse)

[[  3 100  20]
 [200  30   1]
 [ 10   2 300]]


# Sort rows and columns in any order

In [141]:
import numpy as np
a = np.arange(10, 35).reshape(5,5)
print(a)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


## sort column in any order 

In [142]:
col_swap = a[:, [3,2,4,0,1]]
print(col_swap)

[[13 12 14 10 11]
 [18 17 19 15 16]
 [23 22 24 20 21]
 [28 27 29 25 26]
 [33 32 34 30 31]]


In [143]:
col_inverse = a[:, ::-1]
print(col_inverse)

[[14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]
 [29 28 27 26 25]
 [34 33 32 31 30]]


In [144]:
col_select = a[:, [2,4,0]]
print(col_select)
col_select2 = a[:, [2,2,2]]
print(col_select2)

[[12 14 10]
 [17 19 15]
 [22 24 20]
 [27 29 25]
 [32 34 30]]
[[12 12 12]
 [17 17 17]
 [22 22 22]
 [27 27 27]
 [32 32 32]]


## sort rows in any order

In [145]:
row_swap = a[[3,2,4,0,1], :]
print(row_swap)

[[25 26 27 28 29]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [146]:
row_swap = a[[3,2,4,0,1]]
print(row_swap)

[[25 26 27 28 29]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [147]:
row_inverse = a[::-1]
print(row_inverse)

[[30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]]


In [148]:
row_select = a[[2,4,0]]
print(row_select)

[[20 21 22 23 24]
 [30 31 32 33 34]
 [10 11 12 13 14]]


In [149]:
row_select2 = a[[2,2,2]]
print(row_select2)

[[20 21 22 23 24]
 [20 21 22 23 24]
 [20 21 22 23 24]]
