<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/pandas/pandas_DF_S_ndarray_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DataFrame...

In [84]:
import numpy as np
import pandas as pd
df = pd.DataFrame(data = [[1,2,3], [4,5,6]], columns = ['a','b','c'])
print(df)
a_df = df.values
print(a_df)
print(type(a_df))
print(a_df.dtype)

   a  b  c
0  1  2  3
1  4  5  6
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64


In [85]:
s = df['a']
print(s)

0    1
1    4
Name: a, dtype: int64


In [86]:
a_s = s.values
print(a_s)
print(type(a_s))
print(a_s.dtype)

[1 4]
<class 'numpy.ndarray'>
int64


In [87]:
df_f = pd.DataFrame([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print(df_f)
a_df_f = df_f.values
print(a_df_f)
print(type(a_df_f))
print(a_df_f.dtype)

     0    1    2
0  0.1  0.2  0.3
1  0.4  0.5  0.6
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
<class 'numpy.ndarray'>
float64


In [88]:
df_multi = pd.read_csv('./sample_pandas_normal.csv')
print(df_multi)
a_df_multi = df_multi.values
print(a_df_multi)
print(type(a_df_multi))
print(a_df_multi.dtype)

      name  age state  point
0    Alice   24    NY     64
1      Bob   42    CA     92
2  Charlie   18    CA     70
3     Dave   68    TX     70
4    Ellen   24    CA     88
5    Frank   30    NY     57
[['Alice' 24 'NY' 64]
 ['Bob' 42 'CA' 92]
 ['Charlie' 18 'CA' 70]
 ['Dave' 68 'TX' 70]
 ['Ellen' 24 'CA' 88]
 ['Frank' 30 'NY' 57]]
<class 'numpy.ndarray'>
object


In [89]:
a_df_int = df_multi[['age', 'point']].values
print(a_df_int)

[[24 64]
 [42 92]
 [18 70]
 [68 70]
 [24 88]
 [30 57]]


In [90]:
print(a_df_int.T)

[[24 42 18 68 24 30]
 [64 92 70 70 88 57]]


In [91]:
a_df_int = df_multi.select_dtypes(include=int).values
print(a_df_int)

[[24 64]
 [42 92]
 [18 70]
 [68 70]
 [24 88]
 [30 57]]


In [92]:
import numpy as np
import pandas as pd
a = np.arange(4)
print(a)
s = pd.Series(a)
print(s)

[0 1 2 3]
0    0
1    1
2    2
3    3
dtype: int64


In [93]:
index = ['A', 'B', 'C', 'D']
name = 'sample'
s = pd.Series(data = a, index = index, name = name, dtype = 'float')
print(s)

A    0.0
B    1.0
C    2.0
D    3.0
Name: sample, dtype: float64


In [94]:
a = np.arange(12).reshape((4,3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [95]:
s = pd.Series(a[2])
print(s)
s = pd.Series(a.T[2])
print(s)

0    6
1    7
2    8
dtype: int64
0     2
1     5
2     8
3    11
dtype: int64


In [96]:
a = np.arange(12).reshape((4,3))
print(a)
df = pd.DataFrame(a)
print(df)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [97]:
index = ['A', 'B', 'C', 'D']
columns = ['a', 'b', 'c']
df = pd.DataFrame(data = a, index = index, columns=columns, dtype = 'float')
print(df)

     a     b     c
A  0.0   1.0   2.0
B  3.0   4.0   5.0
C  6.0   7.0   8.0
D  9.0  10.0  11.0


In [98]:
df = pd.DataFrame(data = [[1,2,3], [4,5,6]], columns = ['a','b','c'])
print(df)
a_values = df.values
print(a_values)

   a  b  c
0  1  2  3
1  4  5  6
[[1 2 3]
 [4 5 6]]


In [99]:
print(np.shares_memory(a_values, df))
a_values[0,0] = 100
print(a_values)

True
[[100   2   3]
 [  4   5   6]]


In [100]:
print(df)

     a  b  c
0  100  2  3
1    4  5  6


In [102]:
df_if = pd.DataFrame(data = [[1,0.1], [2,0.2]], columns = ['int', 'float'])
print(df)
a_values_if = df_if.values
print(a_values_if)
print(np.shares_memory(a_values_if, df_if))

     a  b  c
0  100  2  3
1    4  5  6
[[1.  0.1]
 [2.  0.2]]
False


In [103]:
print(df)

     a  b  c
0  100  2  3
1    4  5  6


In [104]:
print(df.iloc[:, ::2].values)

[[100   3]
 [  4   6]]


In [105]:
print(np.shares_memory(df.iloc[:, ::2].values, df))

True


In [106]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [107]:
df_a = pd.DataFrame(a, columns = ['a', 'b', 'c'])
print(df_a)

   a  b  c
0  1  2  3
1  4  5  6


In [108]:
df_a.iat[1,0] = 10
print(a)

[[ 1  2  3]
 [10  5  6]]


In [109]:
df = pd.DataFrame(data = [[1,2,3], [4,5,6]], columns = ['a', 'b', 'c'])
print(df)

   a  b  c
0  1  2  3
1  4  5  6


In [112]:
a = df.to_numpy()
print(a)

[[1 2 3]
 [4 5 6]]


In [113]:
print(type(a))

<class 'numpy.ndarray'>


In [114]:
a_copy = df.to_numpy(copy=True)


In [115]:
import pandas as pd
l_1d = [0,1,2]
s = pd.Series(l_1d)
print(s)
s = pd.Series(l_1d, index = ['row1', 'row2', 'row3'])
print(s)

0    0
1    1
2    2
dtype: int64
row1    0
row2    1
row3    2
dtype: int64


In [116]:
l_2d = [[0,1,2], [3,4,5]]
df = pd.DataFrame(l_2d)
print(df)
df = pd.DataFrame(l_2d, index = ['row1', 'row2'], columns = ['col1', 'col2', 'col3'])
print(df)

   0  1  2
0  0  1  2
1  3  4  5
      col1  col2  col3
row1     0     1     2
row2     3     4     5


In [117]:
l_1d_index = [['Alice', 0], ['Bob', 1], ['Charlie', 2]]
index, value = zip(*l_1d_index)
print(index)

('Alice', 'Bob', 'Charlie')


In [119]:
print(value)
s_index = pd.Series(value,index=index)
print(s_index)

(0, 1, 2)
Alice      0
Bob        1
Charlie    2
dtype: int64


In [120]:
l_2d_index = [['Alice', 0, 0.0], ['Bob', 1, 0.1], ['Charlie',2,0.2]]
df_index = pd.DataFrame(l_2d_index, columns = ['name', 'val1', 'val2'])
print(df_index)

      name  val1  val2
0    Alice     0   0.0
1      Bob     1   0.1
2  Charlie     2   0.2


In [121]:
df_index_set = df_index.set_index('name')
print(df_index_set)

         val1  val2
name               
Alice       0   0.0
Bob         1   0.1
Charlie     2   0.2


In [122]:
l_2d_index_columns = [['name', 'val1', 'val2'], ['Alice', 0,0.0], ['Bob', 1, 0.1], ['Charlie', 2, 0.2]]
df_index_columns = pd.DataFrame(l_2d_index_columns[1:], columns = l_2d_index_columns[0])
print(df_index_columns)
df_index_columns_set=df_index_columns.set_index('name')
print(df_index_columns_set)

      name  val1  val2
0    Alice     0   0.0
1      Bob     1   0.1
2  Charlie     2   0.2
         val1  val2
name               
Alice       0   0.0
Bob         1   0.1
Charlie     2   0.2


In [123]:
s = pd.Series([0,1,2])
print(s)
l_1d = s.values.tolist()
print(l_1d)
df = pd.DataFrame([[0,1,2], [3,4,5]])
l_2d = df.values.tolist()
print(l_2d)

0    0
1    1
2    2
dtype: int64
[0, 1, 2]
[[0, 1, 2], [3, 4, 5]]


In [124]:
s_index = pd.Series([0,1,2], index = ['row1', 'row2', 'row3'])
print(s_index)
l_1d = s_index.values.tolist()
print(l_1d)

row1    0
row2    1
row3    2
dtype: int64
[0, 1, 2]


In [127]:
print(s_index.reset_index().values.tolist())

[['row1', 0], ['row2', 1], ['row3', 2]]


In [128]:
print(df_index.reset_index().T.reset_index().T.values.tolist())

[['index', 'name', 'val1', 'val2'], [0, 'Alice', 0, 0.0], [1, 'Bob', 1, 0.1], [2, 'Charlie', 2, 0.2]]


In [129]:
print(s_index)

row1    0
row2    1
row3    2
dtype: int64


In [130]:
print(s_index.index)

Index(['row1', 'row2', 'row3'], dtype='object')


In [131]:
print(s_index.index.tolist())

['row1', 'row2', 'row3']


In [132]:
print(df_index)
print(df_index.index)

      name  val1  val2
0    Alice     0   0.0
1      Bob     1   0.1
2  Charlie     2   0.2
RangeIndex(start=0, stop=3, step=1)


In [133]:
print(df_index.columns.tolist())

['name', 'val1', 'val2']


In [134]:
import pandas as pd
import pprint
from collections import OrderedDict
df = pd.DataFrame({'col1':[1,2,3], 'col2':['a','x','あ']}, index = ['row1','row2','row3'])
print(df)

      col1 col2
row1     1    a
row2     2    x
row3     3    あ


In [135]:
d = df.to_dict()
pprint.pprint(d)
print(type(d))

{'col1': {'row1': 1, 'row2': 2, 'row3': 3},
 'col2': {'row1': 'a', 'row2': 'x', 'row3': 'あ'}}
<class 'dict'>


In [137]:
d_dict = df.to_dict(orient='dict')
pprint.pprint(d_dict)
print(d_dict['col1'])

{'col1': {'row1': 1, 'row2': 2, 'row3': 3},
 'col2': {'row1': 'a', 'row2': 'x', 'row3': 'あ'}}
{'row1': 1, 'row2': 2, 'row3': 3}


In [138]:
d_list = df.to_dict(orient='list')
pprint.pprint(d_list)


{'col1': [1, 2, 3], 'col2': ['a', 'x', 'あ']}


In [139]:
d_series = df.to_dict(orient='series')
pprint.pprint(d_series)

{'col1': row1    1
row2    2
row3    3
Name: col1, dtype: int64,
 'col2': row1    a
row2    x
row3    あ
Name: col2, dtype: object}


In [140]:
d_split = df.to_dict(orient='split')
pprint.pprint(d_split)

{'columns': ['col1', 'col2'],
 'data': [[1, 'a'], [2, 'x'], [3, 'あ']],
 'index': ['row1', 'row2', 'row3']}


In [141]:
l_records = df.to_dict(orient='record')
pprint.pprint(l_records)
print(type(l_records))


[{'col1': 1, 'col2': 'a'}, {'col1': 2, 'col2': 'x'}, {'col1': 3, 'col2': 'あ'}]
<class 'list'>


In [142]:
d_index = df.to_dict(orient='index')
pprint.pprint(d_index)

{'row1': {'col1': 1, 'col2': 'a'},
 'row2': {'col1': 2, 'col2': 'x'},
 'row3': {'col1': 3, 'col2': 'あ'}}


In [143]:
od = df.to_dict(into=OrderedDict)
pprint.pprint(od)

OrderedDict([('col1', OrderedDict([('row1', 1), ('row2', 2), ('row3', 3)])),
             ('col2',
              OrderedDict([('row1', 'a'), ('row2', 'x'), ('row3', 'あ')]))])


In [144]:
print(df.index)

Index(['row1', 'row2', 'row3'], dtype='object')


In [145]:
print(df['col1'])
d_col = dict(zip(df.index, df['col1']))
print(d_col)

row1    1
row2    2
row3    3
Name: col1, dtype: int64
{'row1': 1, 'row2': 2, 'row3': 3}


In [146]:
d_row = dict(zip(df.columns, df.loc['row1']))
print(d_row)

{'col1': 1, 'col2': 'a'}


In [147]:
od = df['col1'].to_dict(OrderedDict)