<a href="https://colab.research.google.com/github/anko191/C/blob/master/numpy/Numpy_dataframe_series_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
df = pd.DataFrame(data = [[1,2,3], [4,5,6]], columns=['a','b','c'])
a = df.to_numpy()
print(a)

[[1 2 3]
 [4 5 6]]


In [51]:
a_copy = df.to_numpy(copy = True)
print(a_copy)
print(np.shares_memory(df, a_copy))
a_copy[0,0] = 10
print(a_copy)
print(df)

[[1 2 3]
 [4 5 6]]
False
[[10  2  3]
 [ 4  5  6]]
   a  b  c
0  1  2  3
1  4  5  6


In [52]:
a_f = df.to_numpy(dtype=float)
print(a_f)
print(np.shares_memory(df, a_f))

[[1. 2. 3.]
 [4. 5. 6.]]
False


# list -> ndarray , numpy.array()
# ndarray -> list, tolist()

In [53]:
l_2d = [[0,1,2], [3,4,5]]
arr_2d = np.array(l_2d)
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [54]:
arr_ld = np.arange(3)
print(arr_ld)
l_ld = arr_ld.tolist()
print(l_ld)

[0 1 2]
[0, 1, 2]
