<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_concatenate_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 結合 concatenate, stack, block

In [ ]:
import numpy as np
a1 = np.ones((2,3), int)
print(a1)

[[1 1 1]
 [1 1 1]]


In [ ]:
a2 = np.full((2,3), 2)
print(a2)

[[2 2 2]
 [2 2 2]]


In [ ]:
print(np.concatenate([a1, a2]))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [ ]:
a3 = np.full((2,3), 3)
print(a3)
print(np.concatenate([a1,a2,a3]))

[[3 3 3]
 [3 3 3]]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [3 3 3]
 [3 3 3]]


In [ ]:
print(np.concatenate([a1,a2], 0))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [ ]:
print(np.concatenate([a1,a2], 1))

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [ ]:
a1 = np.ones(3, int)
print(a1)
a2 = np.full(3,2)
print(a2)
print(np.concatenate([a1,a2], 0))

[1 1 1]
[2 2 2]
[1 1 1 2 2 2]


# numpy.stack()
new dimension

In [ ]:
print(np.stack([a1,a2]))

[[1 1 1]
 [2 2 2]]


In [ ]:
print(np.stack([a1,a2], 1))

[[1 2]
 [1 2]
 [1 2]]


In [ ]:
a2_ = np.full(4,2)
print(a2_)

[2 2 2 2]


In [ ]:
a1 = np.ones((3,4), int)
print(a1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
a2 = np.full((3,4), 2)
print(a2)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
print(np.stack([a1, a2]))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


In [ ]:
print(np.stack([a1, a2], 1))

[[[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]]


In [ ]:
print(np.stack([a1,a2], 1)[:,0,:])

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
print(np.stack([a1,a2], 1)[:,1,:])

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
print(np.stack([a1, a2], 2))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


axis = -1 is last axis... this case is axis = 2

In [ ]:
print(np.stack([a1, a2], -1))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


# numpy.block()
np.block([a1, a2]))

argument type is equal to .block(??)

In [ ]:
a1 = np.ones((2,3), int)
a2 = np.full((2,3),2)
print(np.block([a1, a2]))

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [ ]:
print(np.block([[a1], [a2]]))
print(np.block([[a1, a2], [a2,a1]]))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 1 1 1]
 [2 2 2 1 1 1]]


In [ ]:
print(np.block([[[a1]], [[a2]]]).shape)

(2, 2, 3)


In [ ]:
a3 = np.full(6,3)
print(a)

NameError: ignored

In [ ]:
print(np.block([[a1, a2], [a3]]))

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 3 3 3]]


# numpy.vstack() vertical concatenate^^

In [ ]:
print(np.vstack([a1,a2]))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


# numpy.hstack() is horizontal concatenate^^

In [ ]:
print(a2)

[[2 2 2]
 [2 2 2]]


In [ ]:
print(np.hstack([a1, a2]))

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [ ]:
a1 = np.ones(3,int)
a2 = np.full(3,2)
print(np.hstack([a1, a2]))

[1 1 1 2 2 2]


# numpy.dstack() is depth concatenate^^

In [ ]:
a1 = np.ones((3,4), int)
a2 = np.full((3,4), 2)
print(np.dstack([a1, a2]))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


# np.tile()

In [ ]:
import numpy as np
a = np.arange(3)
print(a)

[0 1 2]


In [ ]:
a_tile = np.tile(a, 3)
print(a_tile)
print(a)

[0 1 2 0 1 2 0 1 2]
[0 1 2]


In [ ]:
print(np.tile(a , (2,3,4)))

[[[0 1 2 0 1 2 0 1 2 0 1 2]
  [0 1 2 0 1 2 0 1 2 0 1 2]
  [0 1 2 0 1 2 0 1 2 0 1 2]]

 [[0 1 2 0 1 2 0 1 2 0 1 2]
  [0 1 2 0 1 2 0 1 2 0 1 2]
  [0 1 2 0 1 2 0 1 2 0 1 2]]]


In [ ]:
a_2d = np.arange(6).reshape(2,3)
print(a_2d)

[[0 1 2]
 [3 4 5]]


In [ ]:
print(np.tile(a_2d, (2, )))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [ ]:
print(np.tile(a_2d, (1,2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


IF you repeat axis = 0, reps = (2,1)

In [ ]:
print(np.tile(a_2d, (2,1)))

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [ ]:
print(np.tile(a_2d, (2,2,2)))

[[[0 1 2 0 1 2]
  [3 4 5 3 4 5]
  [0 1 2 0 1 2]
  [3 4 5 3 4 5]]

 [[0 1 2 0 1 2]
  [3 4 5 3 4 5]
  [0 1 2 0 1 2]
  [3 4 5 3 4 5]]]


# image transition aaaaaaaaaaa

In [ ]:
import numpy as np
from PIL import Image

img = np.array(Image.open('data/src/lena_square.png').rresize((128, 128)))
print(img.shape)
img_tile = np.tile(img, (2,3,1))
print(img_tile.shape)
Image.fromarray(img_tile).save('data/dst/lena_numpy_tile.jpg')

FileNotFoundError: ignored

# numpy.split()

In [1]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a_split = np.split(a,2)
print(type(a_split))
print(len(a_split))

<class 'list'>
2


In [4]:
print(a_split[0])

[[0 1 2 3]
 [4 5 6 7]]


In [5]:
print(type(a_split[0]))

<class 'numpy.ndarray'>


unpack tuple

In [6]:
a0, a1 = np.split(a,2)
print(a0)
print(a1)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# indices_or_sections
整数 int を指定する<br>等分割

uses numpy.array_split() if you are trouble in.


and designate array

In [7]:
a0, a1, a2 = np.split(a, [1,3])
print(a0,a1,a2)

[[0 1 2 3]] [[ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]]


In [8]:
a0, a1 = np.split(a, [1])
print(a0, a1)

[[0 1 2 3]] [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


numpy.split(first, second, third)

third argument is axis !!

In [9]:
a0, a1 = np.split(a, 2, 0)
print(a0,a1)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [10]:
a0, a1 = np.split(a, 2, 1)
print(a0, a1)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [11]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
print(a_3d.shape)

(2, 3, 4)


In [13]:
a0, a1 = np.split(a_3d, 2, 0)
print(a0)
print(a1)
a0, a1 = np.split(a_3d, [1], 2)
print(a0)
print(a1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[13 14 15]
  [17 18 19]
  [21 22 23]]]


In [14]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# numpy.array_split() as much as possible split in equal parts

In [16]:
a0, a1 = np.array_split(a, 2, 0)
print(a0)
print(a1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]]


In [17]:
a0, a1, a2 = np.array_split(a, 3, 1)
print(a0)
print(a1)
print(a2)

[[ 0  1]
 [ 5  6]
 [10 11]]
[[ 2  3]
 [ 7  8]
 [12 13]]
[[ 4]
 [ 9]
 [14]]


# numpy.vsplit() is vertical split

In [18]:
a = np.arange(16).reshape(4,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
a0, a1 = np.vsplit(a,2)
print(a0)
print(a1)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# numpy.hsplit() horizontal split

In [20]:
a = np.arange(16).reshape(4,4)
print(a)
a0, a1 = np.hsplit(a, 2)
print(a0)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [21]:
a_1d = np.arange(6)
print(a_1d)
a0, a1 = np.hsplit(a_1d, 2)
print(a0)
print(a1)

[0 1 2 3 4 5]
[0 1 2]
[3 4 5]


## hsplit is equal parts.
if your argument is 2, split in 2 equal parts.
numpy.hsplit(a, 2)

# numpy.dsplit() is depth

In [23]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)
a0,a1 = np.dsplit(a_3d,2) # same, axis = 2
print(a0)
print(a1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]


designate list


In [24]:
a0, a1 = np.dsplit(a_3d, [1])
print(a0)
print(a1)

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[13 14 15]
  [17 18 19]
  [21 22 23]]]


## numpy.dsplit() is for 3over-dimension only

# split array is view of original array

In [26]:
a = np.arange(16).reshape(4,4)
print(a)
l = np.split(a, 2)
print(l[0])
print(np.shares_memory(a, l[0]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
True


## if you change numerics, original numerics has changed

In [27]:
a[0,0] = 100
print(a)
print(l[0])

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[100   1   2   3]
 [  4   5   6   7]]


## if you process separately, you use 'copy()'.

In [28]:
a = np.arange(16).reshape(4,4)
l_copy = np.split(a.copy(), 2)
print(np.shares_memory(a, l_copy[0]))

False


In [29]:
a[0,0] = 100
print(a)
print(l_copy[0])

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[[0 1 2 3]
 [4 5 6 7]]
