<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_acquisition_transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Geometry acquisition and transformation

In [ ]:
import numpy as np
a_1d = np.arange(3)
print(a_1d)

[0 1 2]


In [ ]:
a_2d = np.arange(12).reshape((3,4))
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a_3d = np.arange(24).reshape((2,3,4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## number of dimension  'ndim'

In [ ]:
print(a_1d.ndim)

1


In [ ]:
print(type(a_1d.ndim))

<class 'int'>


In [ ]:
print(a_2d.ndim)
print(a_3d.ndim)

2
3


## shape is 'shape' ( each size )

In [ ]:
print(a_1d.shape)

(3,)


In [ ]:
print(type(a_1d.shape))

<class 'tuple'>


In [ ]:
print(a_2d.shape)
print(a_3d.shape)

(3, 4)
(2, 3, 4)


In [ ]:
print(a_2d.shape[0])
print(a_2d.shape[1])

3
4


In [ ]:
row, col = a_2d.shape
print(row)

3


In [ ]:
print(col)

4


## size is '.size'
numbers of all elements

In [ ]:
print(a_1d.size)

3


In [ ]:
print(type(a_1d.size))
print(a_2d.size)
print(a_3d.size)

<class 'int'>
12
24


## first dimension size is 'len()'

In [ ]:
print(len(a_1d))
print(a_1d.shape[0])
print(a_1d.size)
print(len(a_2d))

3
3
3
3


In [ ]:
print(a_2d.shape)

(3, 4)


In [ ]:
print(a_2d.shape[0])

3


In [ ]:
print(len(a_3d))
print(a_3d.shape[0])

2
2


# How to use 'reshape' and what means '-1' ?

## ndarray.reshape() method

In [ ]:
import numpy as np
a = np.arange(24)
print(a)
print(a.shape)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1


## numpy.ndarray -> reshape() list or tuple

In [ ]:
a_4_6 = a.reshape([4,6])
print(a_4_6)
print(a_4_6.shape)
print(a_4_6.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [ ]:
a_2_3_4 = a.reshape([2,3,4])
print(a_2_3_4)
print(a_2_3_4.shape)
print(a_2_3_4.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [ ]:
print(a.reshape(4,6))
print(a.reshape(2,3,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## numpy.reshape() can use argument !

In [ ]:
print(np.reshape(a, [4,6]))
print(np.reshape(a, [2,3,4]))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### numpy.reshape(ndarray, [])  VS numpy.ndarray.reshape([]) !?

In [ ]:
print(a.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## order = 'C' : C language, order = 'F' : FORTRAN, obey rows and columns

In [ ]:
print(a.reshape([4,6], order = 'C'))
print(a.reshape([4,6], order = 'F'))
print(a.reshape([2,3,4], order = 'C'))
print(a.reshape([2,3,4], order = 'F'))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]


In [ ]:
print(np.reshape(a, [4,6], order = 'F'))

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


# '-1'
is ' decide automation '

In [ ]:
print(a.reshape([4,-1])) # ok 6 !

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
print(a.reshape([2,-1,4]))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## .reshape() return view  !! This is that memory share each other !

In [ ]:
a = np.arange(8)
print(a)
a_2_4 = a.reshape([2,4])
print(a_2_4)
print(np.shares_memory(a, a_2_4))

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
True


In [ ]:
a[0] = 100
print(a)
print(a_2_4)

[100   1   2   3   4   5   6   7]
[[100   1   2   3]
 [  4   5   6   7]]


In [ ]:
a_2_4[0,0] = 0
print(a_2_4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


## if you copy use 'copy'

In [ ]:
a = np.arange(8)
a_2_4_copy = a.reshape([2,4]).copy()
print(a_2_4_copy)
print(np.shares_memory(a, a_2_4_copy))

[[0 1 2 3]
 [4 5 6 7]]
False


In [ ]:
a[0] = 100
print(a)
print(a_2_4_copy)
a_2_4_copy[0,0] = 200
print(a_2_4_copy)
print(a)

[100   1   2   3   4   5   6   7]
[[0 1 2 3]
 [4 5 6 7]]
[[200   1   2   3]
 [  4   5   6   7]]
[100   1   2   3   4   5   6   7]


In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
a_step = a[:, ::2]
print(a_step)
print(a_step.reshape(-1))
print(np.shares_memory(a_step, a_step.reshape(-1)))

[[0 1 2]
 [3 4 5]]
[[0 2]
 [3 5]]
[0 2 3 5]
False


In [ ]:
a = np.arange(8).reshape(2,4)
print(a)
a_step = a[:, ::2]
print(a_step)
print(a_step.reshape(-1))
print(np.shares_memory(a_step, a_step.reshape(-1)))

[[0 1 2 3]
 [4 5 6 7]]
[[0 2]
 [4 6]]
[0 2 4 6]
True


# Add dimension !? np.newaxis, np.expand_dims()

## np.newaxis is alias for 'None' ( equal )

In [ ]:
import numpy as np
print(np.newaxis is None)

True


### adding new 1 size dimension

In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.shape)
print(a[:, :, np.newaxis])

[[0 1 2]
 [3 4 5]]
(2, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]


In [ ]:
print(a[:, :, np.newaxis].shape)

(2, 3, 1)


In [ ]:
print(a[:, np.newaxis, :])

[[[0 1 2]]

 [[3 4 5]]]


In [ ]:
print(a[:, np.newaxis, :].shape)

(2, 1, 3)


In [ ]:
print(a[np.newaxis, :, :])
print(a[np.newaxis, :, :].shape)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


## []'s end is optional

In [ ]:
print(a[:, np.newaxis])
print(a[:, np.newaxis].shape)

[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)


In [ ]:
print(a[np.newaxis])
print(a[np.newaxis].shape)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


## consective : is replaced by " ... " .     !?

In [ ]:
print(a[..., np.newaxis])
print(a[..., np.newaxis].shape)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)


## multiple ok

In [ ]:
print(a[np.newaxis, :, np.newaxis, :, np.newaxis])

[[[[[0]
    [1]
    [2]]]


  [[[3]
    [4]
    [5]]]]]


In [ ]:
print(a[np.newaxis, :, np.newaxis, :, np.newaxis].shape)

(1, 2, 1, 3, 1)


## control broadcast

In [ ]:
a = np.zeros(27, dtype = np.int).reshape(3,3,3)
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
print(a.shape)
b = np.arange(9).reshape(3,3)
print(b)
print(b.shape)

(3, 3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [ ]:
print(a + b)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]


### omg automation transformation ... a ? 

In [ ]:
print(b[np.newaxis, :, :].shape)

(1, 3, 3)


In [ ]:
print(a + b[np.newaxis, :, :])

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]


### change adding position, then difference result

In [ ]:
print(b[:, np.newaxis, :].shape)
print(a+b[:, np.newaxis, :])

(3, 1, 3)
[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[3 4 5]
  [3 4 5]
  [3 4 5]]

 [[6 7 8]
  [6 7 8]
  [6 7 8]]]


In [ ]:
print(b[:, :, np.newaxis].shape)
print(a + b[:, :, np.newaxis])

(3, 3, 1)
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]
  [5 5 5]]

 [[6 6 6]
  [7 7 7]
  [8 8 8]]]


## np.expand_dims() new dimension

In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
print(np.expand_dims(a, 0))

[[0 1 2]
 [3 4 5]]
[[[0 1 2]
  [3 4 5]]]


In [ ]:
print(np.expand_dims(a,0).shape)

(1, 2, 3)


## new 1 dimension first !

In [ ]:
print(np.expand_dims(a,0).shape)
print(np.expand_dims(a,1).shape)
print(np.expand_dims(a, 2).shape)

(1, 2, 3)
(2, 1, 3)
(2, 3, 1)


## negative numerics is ok

In [ ]:
print(np.expand_dims(a, -1).shape)
print(np.expand_dims(a, -2).shape)
print(np.expand_dims(a, -3).shape)

(2, 3, 1)
(2, 1, 3)
(1, 2, 3)


## reshape do same

In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.shape)
print(a[np.newaxis])
print(a[np.newaxis].shape)
print(np.expand_dims(a,0))
print(np.expand_dims(a, 0).shape)
print(a.reshape(1,2,3))
print(a.reshape(1,2,3).shape)

[[0 1 2]
 [3 4 5]]
(2, 3)
[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)
[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)
[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


## tuple *(ndarray) automatically change

In [ ]:
print(a.reshape(1, *a.shape))
print(a.reshape(1, *a.shape).shape)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


# Transpose and axis switching .

In [ ]:
import numpy as np
a_2d = np.arange(6).reshape(2,3)
print(a_2d)
a_2d_T = a_2d.T
print(a_2d_T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [ ]:
print(np.shares_memory(a_2d, a_2d_T))

True


In [ ]:
a_2d_T[0,1] = 100
print(a_2d_T)

[[  0 100]
 [  1   4]
 [  2   5]]


In [ ]:
print(a_2d)
a_2d[1,0] = 3
print(a_2d)
print(a_2d_T)

[[  0   1   2]
 [100   4   5]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


## ndarray method transpose()

In [ ]:
print(a_2d.transpose())

[[0 3]
 [1 4]
 [2 5]]


## numpy.transpose()

In [ ]:
print(np.transpose(a_2d))

[[0 3]
 [1 4]
 [2 5]]


## ops ! 1 only dimension have no effect !

In [ ]:
a_1d = np.arange(3)
print(a_1d)
print(a_1d.T)
print(a_1d.transpose())
print(np.transpose(a_1d))

[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]


In [ ]:
a_row = a_1d.reshape(1, -1)
print(a_row)
print(a_row.shape)
print(a_row.ndim)

[[0 1 2]]
(1, 3)
2


In [ ]:
a_col = a_1d.reshape(-1,1)
print(a_col)
print(a_col.shape)
print(a_col.ndim)

[[0]
 [1]
 [2]]
(3, 1)
2


In [ ]:
print(a_row.T)
print(a_col.T)

[[0]
 [1]
 [2]]
[[0 1 2]]


## 3 dimension

In [ ]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)
print(a_3d.T)
print(a_3d.T.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)


## can designate (2,1,0), (0,1,2)...

In [ ]:
print(a_3d.transpose(2,1,0))
print(a_3d.transpose(2,1,0).shape)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)


In [ ]:
print(np.transpose(a_3d, (2,1,0)).shape) # tuple only !

(4, 3, 2)


## multiple matrix at once ! n's contents ... (n, rows, columns) can change rows and columns easily!

In [ ]:
print(a_3d)
print(a_3d.shape)
print(a_3d.transpose(0, 2, 1))
print(a_3d.transpose(0,2,1).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
(2, 4, 3)


## if contents (rows, columns, n) ... ?!

In [ ]:
print(a_3d.transpose(1, 0, 2))
print(a_3d.transpose(1,0, 2).shape)
print(a_3d[:,:,0])

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)
[[ 0  4  8]
 [12 16 20]]


In [ ]:
print(a_3d.transpose(1,0,2)[:,:,0])

[[ 0 12]
 [ 4 16]
 [ 8 20]]


# Brouadcast.. rules

In [ ]:
import numpy as np
a = np.zeros((3,3), np.int)
print(a)
print(a.shape)
b = np.arange(3)
print(b)
print(b.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
[0 1 2]
(3,)


In [ ]:
print(a + b)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [ ]:
b_1_3 = b.reshape(1,3)
print(b_1_3)
print(b_1_3.shape)

[[0 1 2]]
(1, 3)


In [ ]:
print(np.tile(b_1_3, (3,1)))

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [ ]:
b_3_1 = b.reshape(3,1)
print(b_3_1)
print(b_3_1.shape)
print(a + b_3_1)

[[0]
 [1]
 [2]]
(3, 1)
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [ ]:
print(np.tile(b_3_1, (1,3)))

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [ ]:
print(b_1_3)
print(b_1_3.shape)
print(b_3_1)
print(b_3_1.shape)
print(b_1_3 + b_3_1)

[[0 1 2]]
(1, 3)
[[0]
 [1]
 [2]]
(3, 1)
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
print(np.tile(b_1_3, (3,1)))
print(np.tile(b_3_1, (1,3)))
print(np.tile(b_1_3, (3,1)) + np.tile(b_3_1, (1,3)))

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
c = np.arange(4)
print(c)
print(c.shape)
print(b_3_1)
print(b_3_1.shape)
print(c + b_3_1)

[0 1 2 3]
(4,)
[[0]
 [1]
 [2]]
(3, 1)
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [ ]:
print(np.tile(c.reshape(1,4), (3,1)))
print(np.tile(b_3_1, (1,4)))
print(np.tile(c.reshape(1,4), (3,1)) + np.tile(b_3_1, (1, 4)))

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [ ]:
a = np.zeros((2,3,4), dtype = np.int)
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [2]:
import numpy as np
a = np.zeros((2,3,4), dtype = np.int)
print(a)
print(a.shape)
b = np.arange(3)
print(b)
print(b.shape)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)
[0 1 2]
(3,)


In [3]:
b_3_1 = b.reshape(3,1)
print(b_3_1)

[[0]
 [1]
 [2]]


In [4]:
print(b_3_1.shape)

(3, 1)


In [5]:
print(a + b_3_1)

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]]


### naaaaaaaaaaaan
NG<br>
(2,3,4)<br>
(　　3)<br>
<br>
OK<br>
(2,3,4)<br>
(　3,1) -> (1,3,1) -> (2,3,4)

## Multiplication broadcasts

## Elemental ( Adamant ) product

In [6]:
a = b = np.arange(3)
print(a)
print(a.shape)

[0 1 2]
(3,)


## you can use a*b or np.multipy(a,b)

In [7]:
print(a * b)
print(np.multiply(a,b))

[0 1 4]
[0 1 4]


## if the shape is different,broadcast.

In [8]:
a_1_3 = a.reshape(1,3)
print(a_1_3)
print(a_1_3.shape)
b_3_1 = b.reshape(3,1)
print(b_3_1)

[[0 1 2]]
(1, 3)
[[0]
 [1]
 [2]]


In [9]:
print(b_3_1.shape)
print(a_1_3 * b_3_1)
print(np.multiply(a_1_3, b_3_1))

(3, 1)
[[0 0 0]
 [0 1 2]
 [0 2 4]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [10]:
print(a)

[0 1 2]


In [11]:
print(b_3_1)

[[0]
 [1]
 [2]]


In [12]:
print(a * b_3_1)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [13]:
print(np.multiply(a, b_3_1))

[[0 0 0]
 [0 1 2]
 [0 2 4]]


# Matrix Product, use 'np.matmul()', @,'np.dot()'

2D @ 2D <br>
(n,m) @ (m,p) = (n,p)<br><br>

1D @ 2D or 2D @ 1D<br>
(m, ) @ (m, p) -> (1, m) @ (m, p) = (1, p) -> (p, )<br>
(n, m)@ (m,　) -> (n, m) @ (m, 1) = (n, 1) -> (n, )<br>

1D @ 1D<br>
(m, ) @ (m, ) -> (1, m) @ (m, 1) = (1, 1) -> scalar<br>

In [15]:
print(a_1_3)

[[0 1 2]]


In [16]:
print(b_3_1)

[[0]
 [1]
 [2]]


In [17]:
print(a_1_3 @ b_3_1)

[[5]]


In [18]:
print(np.matmul(a_1_3, b_3_1))

[[5]]


In [19]:
print(np.dot(a_1_3, b_3_1))

[[5]]


In [20]:
print((a_1_3 @ b_3_1).shape)

(1, 1)


In [21]:
print(a_1_3)
print(b)

[[0 1 2]]
[0 1 2]


In [22]:
print(a_1_3 @ b)
print(np.matmul(a_1_3, b))
print(np.dot(a_1_3, b))
print((a_1_3 @ b).shape)

[5]
[5]
[5]
(1,)


In [23]:
print(a)
print(b)

[0 1 2]
[0 1 2]


In [24]:
print(a @ b)
print(np.matmul(a,b))
print(np.dot(a,b))

5
5
5


In [25]:
a = np.arange(6).reshape(2,3)
print(a)
b = np.arange(2).reshape(1,2)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1]]


In [26]:
print(np.tile(b, (3,1)))
print(a @ np.tile(b, (3,1)))

[[0 1]
 [0 1]
 [0 1]]
[[ 0  3]
 [ 0 12]]


### function to get result of broadcast

#### np.broadcast_to

In [27]:
a = np.arange(3)
print(a.shape)

(3,)


In [28]:
print(np.broadcast_to(a, (3,3)))

[[0 1 2]
 [0 1 2]
 [0 1 2]]


### multiple array broadcasted, : 'np.broadcast_arrays()'

In [29]:
a = np.arange(3)
print(a)
print(a.shape)

[0 1 2]
(3,)


In [34]:
b = np.arange(3).reshape(3,1)
print(b)
print(b.shape)

[[0]
 [1]
 [2]]
(3, 1)


In [32]:
arrays = np.broadcast_arrays(a, b)
print(type(arrays))
print(len(arrays))

<class 'list'>
2


In [33]:
print(arrays[0])
print(arrays[1])
print(type(arrays[0]))

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
<class 'numpy.ndarray'>
