<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_NaN_replacement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.nan -> another values ( replacement )

## NaN 's , occur, generation, determination.

In [89]:
import numpy as np
a = np.genfromtxt('./sample_nan.csv', delimiter=',')
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


## if you generate NaN, use np.nan

In [90]:
a_nan = np.array([0, 1, np.nan, float('nan')])

In [91]:
print(a_nan)

[ 0.  1. nan nan]


## if you determine NaN, use np.isnan() or math.isnan()

In [92]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

False
True


In [93]:
print(a_nan == np.nan)
print(np.isnan(a_nan))

[False False False False]
[False False  True  True]


## use argument in np.genfromtxt().
argument : filling_values = ? if you fill 0, you use filling_values = 0. 
<br> NaN is rearranged 'filling_values'



In [95]:
a_fill = np.genfromtxt('./sample_nan.csv', delimiter=',', filling_values = 0)
print(a_fill)

[[11. 12.  0. 14.]
 [21.  0.  0. 24.]
 [31. 32. 33. 34.]]


## use np.nan_to_num() to rearrange NaN.

In [96]:
a = np.genfromtxt('./sample_nan.csv', delimiter=',')
print(np.nan_to_num(a))
print(a)

[[11. 12.  0. 14.]
 [21.  0.  0. 24.]
 [31. 32. 33. 34.]]
[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


## the second argument 'copy' set 'False', then change original ndarray too.

In [97]:
print(np.nan_to_num(a, copy = False))
print(a)

[[11. 12.  0. 14.]
 [21.  0.  0. 24.]
 [31. 32. 33. 34.]]
[[11. 12.  0. 14.]
 [21.  0.  0. 24.]
 [31. 32. 33. 34.]]


### Numpyversion >= 1.17, the third argument 'nan = ?'.

In [98]:
a = np.genfromtxt('./sample_nan.csv', delimiter=',')
print(np.nan_to_num(a, nan = -1))

[[11. 12. -1. 14.]
 [21. -1. -1. 24.]
 [31. 32. 33. 34.]]


### if you use 'np.nanmean()', replace NaN to average.

In [99]:
print(np.nanmean(a))
print(np.nan_to_num(a, nan = np.nanmean(a)))

23.555555555555557
[[11.         12.         23.55555556 14.        ]
 [21.         23.55555556 23.55555556 24.        ]
 [31.         32.         33.         34.        ]]


### reference bool_index is also great.

In [100]:
a = np.genfromtxt('./sample_nan.csv', delimiter=',')
print(np.isnan(a))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [101]:
a[np.isnan(a)] = 0 # this is.
print(a)

[[11. 12.  0. 14.]
 [21.  0.  0. 24.]
 [31. 32. 33. 34.]]


#### can replace np.nanmean()

In [104]:
a = np.genfromtxt('./sample_nan.csv', delimiter = ',')
a[np.isnan(a)] = np.nanmean(a)
print(a)

[[11.         12.         23.55555556 14.        ]
 [21.         23.55555556 23.55555556 24.        ]
 [31.         32.         33.         34.        ]]


# Delete 'NaN'

In [105]:
import numpy as np
a = np.genfromtxt('./sample_nan.csv', delimiter = ',')
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


In [107]:
print(np.isnan(a))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [108]:
print(~np.isnan(a))

[[ True  True False  True]
 [ True False False  True]
 [ True  True  True  True]]


In [109]:
print(a[~np.isnan(a)])

[11. 12. 14. 21. 24. 31. 32. 33. 34.]


In [110]:
print(np.isnan(a).any(axis = 1))

[ True  True False]


In [111]:
print(~np.isnan(a).any(axis = 1))

[False False  True]


In [112]:
print(a[~np.isnan(a).any(axis = 1), :])

[[31. 32. 33. 34.]]


In [113]:
print(a[~np.isnan(a).any(axis = 1)])

[[31. 32. 33. 34.]]


In [114]:
print(~np.isnan(a).any(axis = 0))

[ True False False  True]


In [115]:
print(a[:, ~np.isnan(a).any(axis = 0)])

[[11. 14.]
 [21. 24.]
 [31. 34.]]


### all delete

In [117]:
a = np.genfromtxt('./sample_nan.csv', delimiter = ',')
a[2,2] = np.nan
print(a)
print(a[:, ~np.isnan(a).any(axis = 0)])

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. nan 34.]]
[[11. 14.]
 [21. 24.]
 [31. 34.]]


In [118]:
print(a[:, ~np.isnan(a).all(axis = 0)])

[[11. 12. 14.]
 [21. nan 24.]
 [31. 32. 34.]]
