<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_where_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.where depending on the condition

numpy.where(condition[, x, y])<br>
Return elements, either from x or y, depending on condition.<br>
If only condition is given, return condition.nonzero().<br>

numpy.where()は、条件式conditionを満たす場合、Trueの場合は、 x , <br>満たさない場合 Falseの場合は y とする **ndarray を返す。**<br>

x,yを省略した場合は、条件を満たすindexを返す。<br>

In [ ]:
import numpy as np
a = np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(np.where(a < 4, -1, 100)) # conditon, x, y

[[ -1  -1  -1]
 [ -1 100 100]
 [100 100 100]]


In [ ]:
print(np.where(a < 4, True, False))
print(a < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]
[[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
print(np.where((a > 2 ) & (a < 6), -1, 100))
print(np.where((a > 2) & (a < 6) | (a == 7), -1, 100))

[[100 100 100]
 [ -1  -1  -1]
 [100 100 100]]
[[100 100 100]
 [ -1  -1  -1]
 [100  -1 100]]


## np.where 使わなくても ndarray だけでいけるよ

In [ ]:
print((a > 2) & (a < 6))

[[False False False]
 [ True  True  True]
 [False False False]]


In [ ]:
print(np.where(a < 4, -1, a))
print(np.where(a < 4, a, 100))

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]
[[  0   1   2]
 [  3 100 100]
 [100 100 100]]


In [ ]:
a_org = np.arange(9).reshape((3,3))
print(a_org)
a_new = np.where(a_org < 4, -1, a_org)
print(a_new)
# dont change
print(a_org)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### if you change original

In [ ]:
a_org[a_org < 4] = -1
print(a_org)

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


### can return calculated array

In [ ]:
print(np.where(a < 4, a * 10, a))

[[ 0 10 20]
 [30  4  5]
 [ 6  7  8]]


### if you dont write x and y, return indexes fill condition.

In [ ]:
print(np.where(a < 4))

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))


In [ ]:
print(type(np.where(a < 4)))

<class 'tuple'>


### You can get a list of each coordirate using list(), zip() and '*'

In [3]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(list(zip(*np.where(a < 4))))

[(0, 0), (0, 1), (0, 2), (1, 0)]


In [4]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
print(list(zip(*np.where(a_3d < 15))))

[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 0, 3), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 1, 3), (0, 2, 0), (0, 2, 1), (0, 2, 2), (0, 2, 3), (1, 0, 0), (1, 0, 1), (1, 0, 2)]


#### 1-dimension is ...

In [6]:
a_1d = np.arange(6)
print(np.where(a_1d < 3))

(array([0, 1, 2]),)


In [7]:
print(list(zip(*np.where(a_1d < 3))))

[(0,), (1,), (2,)]


In this case, not tuple of number of elements:1 but 'ndarray' elements of int.
<br>If you want to convert list, using 'tolist()'

In [8]:
print(np.where(a_1d < 3)[0])

[0 1 2]


In [10]:
print(np.where(a_1d < 3)[0].tolist())

[0, 1, 2]


# Extract and delete elements, rows, and columns that meet the criteria.

## Extract elements of satisfying the conditions.

In [11]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(a < 5)
print(a[a < 5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[0 1 2 3 4]


In [12]:
print(a < 10)
print(a[a < 10])

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
b = a[a < 10]
print(b)

[0 1 2 3 4 5 6 7 8 9]


## can use sum(), mean(), max(), min(), std()

In [15]:
print(a[a < 5].sum())
print(a[a < 5].mean())
print(a[a < 5].max())
print(a[a < 10].min())
print(a[a < 10].std())

10
2.0
4
0
2.8722813232690143


### if you use np.all() and np.any(), we can extract rows and columns with keeping the dimensionality.
<br>numpy.all() : extract rows and columns that all elements meet the conditions<br>
nummpy.any() : extract rows and columns that have at least one element that satisfies the condition.

In [17]:
print(a < 5)
print(np.all(a < 5))
print(np.all(a < 5, axis = 0)) # columns
print(np.all(a < 5, axis = 1)) # rows

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
False
[False False False False]
[ True False False]


In [18]:
print(a < 10)
print(np.all(a < 10, axis = 0))
print(np.all(a < 10, axis = 1))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]]
[ True  True False False]
[ True  True False]


### 'Index Reference' : [rows, columns]

In [19]:
print(a[:, np.all(a < 10, axis = 0)])
print(a[np.all(a < 10, axis = 1), :])
print(a[np.all(a < 10, axis = 1)])

[[0 1]
 [4 5]
 [8 9]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [20]:
print(a[:, np.all(a < 5, axis = 0)])

[]


In [21]:
print(a[np.all(a < 5, axis = 1)])
print(a[np.all(a < 5, axis = 1)].ndim)
print(a[np.all(a < 5, axis = 1)].shape)

[[0 1 2 3]]
2
(1, 4)


#### numpy.any()

have at least one element

In [22]:
print(a < 5)
print(np.any(a < 5))
print(np.any(a < 5, axis = 0))
print(np.any(a < 5, axis = 1))

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
True
[ True  True  True  True]
[ True  True False]


In [23]:
print(a[:, np.any(a < 5, axis = 0)]) # all elements
print(a[np.any(a < 5, axis = 1)])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]


### delete this, using ~ , numpy.delete() and numpy.where()

In [24]:
print(a[~(a < 5)])
print(a[:, np.all(a < 10, axis = 0)])
print(a[:, ~np.all(a < 10, axis = 0)])

[ 5  6  7  8  9 10 11]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [25]:
print(a[np.any(a < 5, axis = 1)])
print(a[~np.any(a < 5, axis = 1)])

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]


In [27]:
print(a)
print(np.delete(a, [0,2], axis = 0)) # difference... axis = 0 is deleting 'rows'.
print(np.delete(a, [0, 2], axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[4 5 6 7]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [28]:
print(a < 2)
print(np.where(a < 2))

[[ True  True False False]
 [False False False False]
 [False False False False]]
(array([0, 0]), array([0, 1]))


In [29]:
print(np.where(a < 2)[0])
print(np.where(a < 2)[1])

[0 0]
[0 1]


### combination this two functions ^-^

In [32]:
print(np.delete(a, np.where(a < 2)[0], axis = 0))
print(np.delete(a, np.where(a < 2)[1], axis = 1))
print(a == 6)
print(np.where(a == 6))
print(np.delete(a, np.where(a == 6)))
print(np.delete(a, np.where(a == 6)[0], axis = 0))
print(np.delete(a, np.where(a == 6)[1], axis = 1))

[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[False False False False]
 [False False  True False]
 [False False False False]]
(array([1]), array([2]))
[ 0  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


### multiple condition

In [33]:
print(a[(a < 10) & (a % 2 == 1)] )

[1 3 5 7 9]


In [34]:
print(a[np.any((a == 2) | (a == 10), axis = 1)])

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [36]:
print(np.any((a == 2),axis = 1))

[ True False False]


In [37]:
print(np.any((a == 10), axis = 1))

[False False  True]


In [39]:
print(np.any((a == 2) | (a == 10), axis = 1))

[ True False  True]


In [40]:
# 該当する行を抽出してるだけ any だから　deleteしたわけじゃない

In [41]:
print(a[:, ~np.any((a == 2) | (a == 10), axis = 0)])

[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


# Count Number of Elements

In [1]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(a < 4)
print(a % 2 == 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


## if you use np.count_nonzero() , count True numbers

In [2]:
print(np.count_nonzero(a < 4))
print(np.count_nonzero(a%2 == 1))

4
6


### or use np.sum()

In [3]:
print(np.sum(a < 4))
print(np.sum(a % 2 == 1))

4
6


### if you designate 'axis' in np.count_nonzero(), process each axis !

In [4]:
print(np.count_nonzero(a < 4, axis = 0))
print(np.count_nonzero(a <4 , axis = 1))

[1 1 1 1]
[4 0 0]


In [5]:
print(np.count_nonzero(a % 2 == 1, axis = 0))
print(np.count_nonzero(a % 2 == 1, axis = 1))

[0 3 0 3]
[2 2 2]


## numpy.any() is ok ? in ndarray

In [6]:
print(np.any(a < 4))
print(np.any(a >100))

True
False


In [7]:
print(np.any(a < 4, axis = 0))
print(np.any(a < 4, axis = 1))

[ True  True  True  True]
[ True False False]


## numpy.all() is ok ? 

In [8]:
print(np.all(a < 4))
print(np.all(a < 100))

False
True


In [11]:
print(np.all(a < 4, axis = 0))

[False False False False]


In [10]:
print(np.all(a < 4, axis = 1))

[ True False False]


# multiple Condition

In [12]:
print((a < 4) | (a % 2 == 1))

[[ True  True  True  True]
 [False  True False  True]
 [False  True False  True]]


In [13]:
print(np.count_nonzero((a < 4) | (a % 2 == 1)))

8


In [14]:
print(np.count_nonzero((a < 4) | (a % 2 == 1), axis = 0))
print(np.count_nonzero((a < 4) | (a % 2 == 1), axis = 1))

[1 3 1 3]
[4 2 2]


# Count 'NaN' and 'inf'

In [16]:
a_nan = np.genfromtxt('./sample_nan.csv', delimiter = ',')
print(a_nan)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


make NaN by np.nan and float('nan')

### if you count NaN, use 'np.isnan()'.

In [17]:
print(np.nan == np.nan) # nan is not comparable

False


In [18]:
print(a_nan == np.nan) # no !

[[False False False False]
 [False False False False]
 [False False False False]]


In [19]:
print(np.isnan(a_nan)) # but we can count NaN by using np.isnan()

[[False False  True False]
 [False  True  True False]
 [False False False False]]


# apply np.count_nonzero(np.isnan())

In [20]:
print(np.count_nonzero(np.isnan(a_nan)))
print(np.count_nonzero(np.isnan(a_nan), axis = 0))

3
[0 1 2 0]


In [21]:
print(np.count_nonzero(np.isnan(a_nan), axis = 1))

[1 2 0]


## if you count 'not NaN', use ~.

In [22]:
print(~np.isnan(a_nan))

[[ True  True False  True]
 [ True False False  True]
 [ True  True  True  True]]


# use 'np.isinf()'

In [23]:
a_inf = np.array([-np.inf, 0, np.inf])
print(a_inf)
print(np.isinf(a_inf))

[-inf   0.  inf]
[ True False  True]


## Unlike 'NaN', you can use '=='. 

In [24]:
print(a_inf == np.inf)
print(a_inf == -np.inf)

[False False  True]
[ True False False]
