<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_contents%2Crow%2Ccolumns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Base

In [130]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [131]:
print(a_3d[0,1,2])

6


In [132]:
print(a_3d[1, [True, False, True], ::2])

[[12 14]
 [20 22]]


In [133]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)
print(a_2d[:2, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]


In [134]:
print(a_2d[:2, :])
print(a_2d[:2])

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


## boolean index

In [135]:
a_1d = np.arange(4)
print(a_1d)
print(a_1d[[True, False, True, False]])
print(a_1d[np.array([True, False, True, False])])

[0 1 2 3]
[0 2]
[0 2]


In [136]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)
print(a_2d[[True, False, True]])
print(a_2d[:, [True, False,True,False]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


### multi booling index occurs error
uses np.ix_

In [137]:
print(a_2d[[True, False, True], [True, False, True, False]])
print(a_2d[np.ix_([True, False, True], [True, False, True, False])])

[ 0 10]
[[ 0  2]
 [ 8 10]]


In [138]:
print(a_2d > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [139]:
print(a_2d[a_2d > 5])

[ 6  7  8  9 10 11]


In [141]:
print((a_2d > 5) & (a_2d < 10))

[[False False False False]
 [False False  True  True]
 [ True  True False False]]


# Fancy index ???

In [142]:
a_1d = np.arange(4)
print(a_1d)

[0 1 2 3]


In [143]:
print(a_1d[[0,2]])

[0 2]


In [144]:
print(a_1d[[0,3,2,1,2,-1,-2]])

[0 3 2 1 2 3 2]


In [145]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [146]:
print(a_2d[np.ix_([0,2], [0,2])])

[[ 0  2]
 [ 8 10]]


In [147]:
print(a_2d[np.ix_([0,2,1,1,-1,-1], [0,2,1,3])])

[[ 0  2  1  3]
 [ 8 10  9 11]
 [ 4  6  5  7]
 [ 4  6  5  7]
 [ 8 10  9 11]
 [ 8 10  9 11]]


In [148]:
print(a_2d[:,[1]])

[[1]
 [5]
 [9]]


In [149]:
print(a_2d[:, [1]].shape)

(3, 1)


In [150]:
print(a_2d[:,1])

[1 5 9]


In [151]:
print(a_2d[:,1].shape)

(3,)


3-dimension

In [152]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [154]:
print(a_3d[:, :2, [True, False, True, False]])

[[[ 0  2]
  [ 4  6]]

 [[12 14]
  [16 18]]]


## np.ix_() is error using slice
use range()

In [155]:
print(a_3d[np.ix_(range(2), [0,2], [0,2])])

[[[ 0  2]
  [ 8 10]]

 [[12 14]
  [20 22]]]


In [159]:
print(a_3d[np.ix_(range(a_3d.shape[0]), [0,2], [0,2])])

[[[ 0  2]
  [ 8 10]]

 [[12 14]
  [20 22]]]


## add new numerics using np.ix_()

In [160]:
a_2d = np.arange(12).reshape(3,4)
a_2d[np.ix_([False, True, True], [1,3])] = 200
print(a_2d)

[[  0   1   2   3]
 [  4 200   6 200]
 [  8 200  10 200]]


In [161]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)
print(a_2d[::2, :3])
print(np.arange(6).reshape(2,3) * 100)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 8  9 10]]
[[  0 100 200]
 [300 400 500]]


In [162]:
a_2d[::2,:3] = np.arange(6).reshape(2,3) * 100
print(a_2d)

[[  0 100 200   3]
 [  4   5   6   7]
 [300 400 500  11]]


# view and copy

In [163]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)
a_slice = a_2d[:2, :2]
print(a_slice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]]


In [164]:
print(np.shares_memory(a_2d, a_slice))

True


If it's view, change each other.

In [165]:
a_slice[0,0] = 100
print(a_slice)

[[100   1]
 [  4   5]]


In [166]:
print(a_2d)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [167]:
a_2d[0,0] = 0
print(a_2d)
print(a_slice)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]]


In [168]:
a_fancy_index = a_2d[[0,1]]
print(a_fancy_index)

[[0 1 2 3]
 [4 5 6 7]]


In [169]:
print(np.shares_memory(a_2d, a_fancy_index))

False


In [170]:
a = np.arange(12).reshape((3,4))
print(a)
a[1:, ::2] = [[100,200], [300,400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   2   3]
 [100   5 200   7]
 [300   9 400  11]]


In [171]:
a = np.arange(12).reshape((3,4))
print(a)
a_slice_copy = a[1:, 1:3].copy()
print(a_slice_copy)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]


In [172]:
a_slice_copy[0,0] = 100
print(a_slice_copy)

[[100   6]
 [  9  10]]


In [173]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [174]:
print(a[[0,2], 1:3])

[[ 1  2]
 [ 9 10]]


# Fancy index = designate list[]

In [176]:
a[[0,2], 1:3] = [[100,200],[300,400]]
print(a)

[[  0 100 200   3]
 [  4   5   6   7]
 [  8 300 400  11]]


In [178]:
a_subset = a[[0,2], 1:3]
print(a_subset)
a_subset[0,0] = -1
print(a_subset)
print(a)

[[100 200]
 [300 400]]
[[ -1 200]
 [300 400]]
[[  0 100 200   3]
 [  4   5   6   7]
 [  8 300 400  11]]


In [179]:
a = np.arange(10) * 10
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [180]:
print(a[[5,8]])

[50 80]


In [181]:
idx = np.array([[5,4], [8,0]])
print(idx)

[[5 4]
 [8 0]]


In [182]:
print(a[idx])

[[50 40]
 [80  0]]


In [184]:
idxs = np.ix_([0,2], [1,3])
print(idxs)

(array([[0],
       [2]]), array([[1, 3]]))


In [185]:
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [187]:
print(a_2d[np.ix_([0,2], [1,3])])

[[ 1  3]
 [ 9 11]]


In [188]:
print(a_2d[np.ix_([2,0], [3,3,3])])

[[11 11 11]
 [ 3  3  3]]


In [189]:
print(a_2d[[0,2]][:, [1,3]])

[[ 1  3]
 [ 9 11]]


In [190]:
a_2d[np.ix_([0,2], [1,3])] = [100,200]
print(a_2d)

[[  0 100   2 200]
 [  4   5   6   7]
 [  8 100  10 200]]


In [192]:
a_2d[np.ix_([0,2], [1,3])] = [[100,200], [300,400]]
print(a_2d)

[[  0 100   2 200]
 [  4   5   6   7]
 [  8 300  10 400]]


## combination with slice

In [193]:
a_2d = np.arange(12).reshape((3,4))
print(a_2d)
print(a_2d[[2,0], ::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11 10  9  8]
 [ 3  2  1  0]]


In [194]:
print(a_2d[::2, [3,0,1]])

[[ 3  0  1]
 [11  8  9]]


# append

In [196]:
import numpy as np
a = np.arange(3)
print(a)

[0 1 2]


made new arrangement (array)

In [197]:
a_append = np.append(a,3)
print(a_append)
print(a)

[0 1 2 3]
[0 1 2]


In [198]:
print(np.append(a, [3,4,5]))
print(np.append(a, np.arange(3,6)))

[0 1 2 3 4 5]
[0 1 2 3 4 5]


append front of array

In [199]:
print(np.append(np.arange(-3,0), a))

[-3 -2 -1  0  1  2]


## 2-dimension's np.append()

In [200]:
a_2d = np.arange(6).reshape(2,3)
print(a_2d)
print(np.append(a_2d, 10))

[[0 1 2]
 [3 4 5]]
[ 0  1  2  3  4  5 10]


In [201]:
a_2d_ex = np.arange(6).reshape(2,3) * 10
print(a_2d_ex)
print(np.append(a_2d, a_2d_ex))

[[ 0 10 20]
 [30 40 50]]
[ 0  1  2  3  4  5  0 10 20 30 40 50]


### if you keep dimension, use axis = 0 or axis = 1

In [202]:
print(np.append(a_2d, a_2d_ex, axis = 0))

[[ 0  1  2]
 [ 3  4  5]
 [ 0 10 20]
 [30 40 50]]


In [203]:
print(np.append(a_2d, a_2d_ex, axis = 1))

[[ 0  1  2  0 10 20]
 [ 3  4  5 30 40 50]]


### if you dont match rows and cols, occur error.

In [204]:
print(np.append(a_2d_ex, a_2d, axis = 0))
print(np.append(a_2d_ex, a_2d, axis = 1))

[[ 0 10 20]
 [30 40 50]
 [ 0  1  2]
 [ 3  4  5]]
[[ 0 10 20  0  1  2]
 [30 40 50  3  4  5]]


In [205]:
print(np.append(a_2d, [[0,10,20], [30,40,50]], axis = 0))

[[ 0  1  2]
 [ 3  4  5]
 [ 0 10 20]
 [30 40 50]]


### .reshape() is great way

In [209]:
a_row_1d = np.arange(3)*10
a_row_2d = np.arange(3).reshape(1,3) * 100
print(a_row_2d)
print(np.append(a_2d, a_row_2d, axis = 0))

[[  0 100 200]]
[[  0   1   2]
 [  3   4   5]
 [  0 100 200]]


In [210]:
a_col_2d = np.arange(2).reshape(2,1) * 100
print(a_col_2d)
print(np.append(a_2d, a_col_2d, axis = 1))

[[  0]
 [100]]
[[  0   1   2   0]
 [  3   4   5 100]]


# np.vstack() is connecting array on vertical

In [211]:
print(np.vstack([a_2d, a_row_1d]))

[[ 0  1  2]
 [ 3  4  5]
 [ 0 10 20]]


In [213]:
print(np.vstack([a_row_2d, a_2d, a_row_1d, [[0,-1,-2], [-3,-4,-5]]]))

[[  0 100 200]
 [  0   1   2]
 [  3   4   5]
 [  0  10  20]
 [  0  -1  -2]
 [ -3  -4  -5]]


# np.hstack() is connecting array on horizontal

In [214]:
print(np.hstack([a_col_2d, a_2d, np.arange(2).reshape(2,1) * 10, [[0,-1], [-2,-3]]]))

[[  0   0   1   2   0   0  -1]
 [100   3   4   5  10  -2  -3]]


In [215]:
a_3d_ex = np.arange(12).reshape(2,3,2) * 10
print(a_3d_ex)
print(a_3d_ex.shape)

[[[  0  10]
  [ 20  30]
  [ 40  50]]

 [[ 60  70]
  [ 80  90]
  [100 110]]]
(2, 3, 2)


In [218]:
a_3d = np.arange(12).reshape(2,3,2)
print(a_3d)
print(np.append(a_3d, a_3d_ex, axis = 0))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[  0   1]
  [  2   3]
  [  4   5]]

 [[  6   7]
  [  8   9]
  [ 10  11]]

 [[  0  10]
  [ 20  30]
  [ 40  50]]

 [[ 60  70]
  [ 80  90]
  [100 110]]]


In [219]:
print(np.append(a_3d, a_3d_ex, axis = 0).shape)

(4, 3, 2)


In [220]:
print(np.append(a_3d, a_3d_ex, axis = 1))

[[[  0   1]
  [  2   3]
  [  4   5]
  [  0  10]
  [ 20  30]
  [ 40  50]]

 [[  6   7]
  [  8   9]
  [ 10  11]
  [ 60  70]
  [ 80  90]
  [100 110]]]


In [221]:
print(np.append(a_3d, a_3d_ex, axis = 1).shape)

(2, 6, 2)


In [222]:
print(np.append(a_3d, a_3d_ex, axis = 2))
print(np.append(a_3d,a_3d_ex, axis = 2).shape)

[[[  0   1   0  10]
  [  2   3  20  30]
  [  4   5  40  50]]

 [[  6   7  60  70]
  [  8   9  80  90]
  [ 10  11 100 110]]]
(2, 3, 4)


# To using np.concatenate() is able to connect multi array

In [224]:
print(np.concatenate([a_3d_ex, a_3d, a_3d_ex], axis = 2))

[[[  0  10   0   1   0  10]
  [ 20  30   2   3  20  30]
  [ 40  50   4   5  40  50]]

 [[ 60  70   6   7  60  70]
  [ 80  90   8   9  80  90]
  [100 110  10  11 100 110]]]


# Insert
argument:<br>
* arr
* obj
* value
*axis

In [225]:
a = np.arange(4)
print(a)
print(np.insert(a, 2, 100))

[0 1 2 3]
[  0   1 100   2   3]


In [227]:
print(np.insert(a,1,[100,101,102]))
print(np.insert(a, [0,2,4], [100,101,102]))

[  0 100 101 102   1   2   3]
[100   0   1 101   2   3 102]


## delete

In [228]:
_a = np.insert(a, 1, [100,101,102])
_a = np.delete(_a, 4)
print(_a)

[  0 100 101 102   2   3]


In [229]:
a = np.arange(12).reshape((3,4))
print(a)
print(np.insert(a,2,100))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[  0   1 100   2   3   4   5   6   7   8   9  10  11]


In [230]:
print(np.insert(a,2,100,axis=0))

[[  0   1   2   3]
 [  4   5   6   7]
 [100 100 100 100]
 [  8   9  10  11]]


In [231]:
b1 = np.arange(100,104)
print(b1)
print(np.insert(a, 1, b1, axis = 0))

[100 101 102 103]
[[  0   1   2   3]
 [100 101 102 103]
 [  4   5   6   7]
 [  8   9  10  11]]


In [232]:
print(np.insert(a, 3, b1, axis = 0))
print(np.insert(a, [0,2], b1, axis = 0))

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 101 102 103]]
[[100 101 102 103]
 [  0   1   2   3]
 [  4   5   6   7]
 [100 101 102 103]
 [  8   9  10  11]]


### insert 2-dimension

In [233]:
b2 = np.arange(100,112).reshape((3,4))
print(b2)
print(np.insert(a,2,b2,axis = 0))

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
[[  0   1   2   3]
 [  4   5   6   7]
 [100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [  8   9  10  11]]


In [234]:
print(np.insert(a,2,b2[2], axis = 0))

[[  0   1   2   3]
 [  4   5   6   7]
 [108 109 110 111]
 [  8   9  10  11]]


In [235]:
print(np.insert(a,range(3), b2, axis = 0))

[[100 101 102 103]
 [  0   1   2   3]
 [104 105 106 107]
 [  4   5   6   7]
 [108 109 110 111]
 [  8   9  10  11]]


In [236]:
print(np.vstack((a,b1)))
print(np.vstack((b2,a)))

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 101 102 103]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [237]:
_a = a.copy()

In [238]:
_a[2] = b1
print(_a)

[[  0   1   2   3]
 [  4   5   6   7]
 [100 101 102 103]]


In [240]:
_a = a.copy()
_a[1] = b2[1]
print(_a)

[[  0   1   2   3]
 [104 105 106 107]
 [  8   9  10  11]]


In [241]:
_a = a.copy()
_a[1:] = b2[[0,2]]
print(_a)

[[  0   1   2   3]
 [100 101 102 103]
 [108 109 110 111]]


## insert to columns

In [242]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [243]:
print(np.insert(a,1,100,axis = 1))

[[  0 100   1   2   3]
 [  4 100   5   6   7]
 [  8 100   9  10  11]]


In [244]:
c1 = np.arange(100,103)
print(c1)

[100 101 102]


In [245]:
print(np.insert(a, 1, c1, axis = 1))
print(np.insert(a, 3, c1, axis = 1))

[[  0 100   1   2   3]
 [  4 101   5   6   7]
 [  8 102   9  10  11]]
[[  0   1   2 100   3]
 [  4   5   6 101   7]
 [  8   9  10 102  11]]


-> 2-dimension is attention !

In [246]:
c2 = np.arange(100,106).reshape((3,2))
print(c2)
print(np.insert(a, [1], c2, axis = 1))
print(np.insert(a,[0,2], c2, axis = 1))

[[100 101]
 [102 103]
 [104 105]]
[[  0 100 101   1   2   3]
 [  4 102 103   5   6   7]
 [  8 104 105   9  10  11]]
[[100   0   1 101   2   3]
 [102   4   5 103   6   7]
 [104   8   9 105  10  11]]


### assumption is different ... ? show below

In [247]:
print(c1)

[100 101 102]


In [248]:
print(np.insert(a, 1, c1, axis = 1))

[[  0 100   1   2   3]
 [  4 101   5   6   7]
 [  8 102   9  10  11]]


In [249]:
print(np.insert(a, [1], c1, axis = 1))

[[  0 100 101 102   1   2   3]
 [  4 100 101 102   5   6   7]
 [  8 100 101 102   9  10  11]]


In [250]:
print(np.insert(a, [1,3,4], c1, axis = 1))

[[  0 100   1   2 101   3 102]
 [  4 100   5   6 101   7 102]
 [  8 100   9  10 101  11 102]]


In [251]:
_c1 = c1.reshape((3,1))
print(_c1)

[[100]
 [101]
 [102]]


In [252]:
print(np.insert(a, 1 , _c1, axis = 1))

[[  0 100 101 102   1   2   3]
 [  4 100 101 102   5   6   7]
 [  8 100 101 102   9  10  11]]


In [253]:
print(np.insert(a, [1], _c1, axis = 1))

[[  0 100   1   2   3]
 [  4 101   5   6   7]
 [  8 102   9  10  11]]


In [254]:
print(np.insert(a, [1,3,4], _c1, axis = 1))

[[  0 100   1   2 100   3 100]
 [  4 101   5   6 101   7 101]
 [  8 102   9  10 102  11 102]]


# numpy.hstack() stand and end

In [255]:
print(_c1)

[[100]
 [101]
 [102]]


In [256]:
print(np.hstack((a,_c1)))

[[  0   1   2   3 100]
 [  4   5   6   7 101]
 [  8   9  10  11 102]]


In [257]:
print(np.hstack((_c1,a)))

[[100   0   1   2   3]
 [101   4   5   6   7]
 [102   8   9  10  11]]


In [258]:
print(np.hstack((a,c2)))
print(np.hstack((c2,a)))

[[  0   1   2   3 100 101]
 [  4   5   6   7 102 103]
 [  8   9  10  11 104 105]]
[[100 101   0   1   2   3]
 [102 103   4   5   6   7]
 [104 105   8   9  10  11]]


In [259]:
_a = a.copy()
_a[:,1] = c1
print(_a)

[[  0 100   2   3]
 [  4 101   6   7]
 [  8 102  10  11]]


# np.delete
arguments
* arr
* obj
* axis

In [260]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [261]:
a_del = np.delete(a, 1, 0)
print(a_del)
print(a)

[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [262]:
print(np.delete(a, 0, 0))

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [263]:
print(np.delete(a, 2, 0))

[[0 1 2 3]
 [4 5 6 7]]


In [264]:
print(np.delete(a,1,0))

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [265]:
print(np.delete(a,1,1))

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [266]:
print(np.delete(a, 1, None))
print(np.delete(a, 1))

[ 0  2  3  4  5  6  7  8  9 10 11]
[ 0  2  3  4  5  6  7  8  9 10 11]


## delete multiple rows and cols

In [267]:
print(np.delete(a, [0, 3], 1))
print(np.delete(a, [0, 1, 3], 1))

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 2]
 [ 6]
 [10]]


### using .slice()
* (start,stop,step)

In [269]:
print(np.delete(a, slice(2), 1)) # 0,1
print(np.delete(a, slice(1, 3), 1)) # 1 ~ 2
print(np.delete(a, slice(None, None, 2), 1)) # 0,2

[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 0  3]
 [ 4  7]
 [ 8 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


### using np.s_ ?  if you write [start:stop:step]

In [270]:
print(np.delete(a, np.s_[:2], 1))
print(np.delete(a, np.s_[1:3], 1))
print(np.delete(a, np.s_[::2], 1))

[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 0  3]
 [ 4  7]
 [ 8 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


# multi matrix , delete() repeated

In [276]:
print(a)
print(np.delete(np.delete(a, 1, 0), 1, 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 8 10 11]]


### 3-dimension way

In [280]:
a_3d = np.arange(24).reshape(2,3,4)
print(a_3d)
print(a_3d.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [281]:
print(np.delete(a_3d, 1, 0))
print(np.delete(a_3d, 1, 1))
print(np.delete(a_3d, 1, 2)) # (:,:,1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]
[[[ 0  2  3]
  [ 4  6  7]
  [ 8 10 11]]

 [[12 14 15]
  [16 18 19]
  [20 22 23]]]


In [283]:
print(np.delete(a_3d, [0,3], 2)) # (:,:,[0,3])
print(np.delete(a_3d, np.s_[::2], 2))

[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[13 14]
  [17 18]
  [21 22]]]
[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]]
