<a href="https://colab.research.google.com/github/anko191/C/blob/master/numpy/Numpy_show.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

precision, floatmode

In [1]:
import numpy as np
print(np.get_printoptions())

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}


In [2]:
a = np.array([12.3456, 0.123456789])
print(a)

[12.3456      0.12345679]


In [3]:
np.set_printoptions(precision=3)
print(a)

[12.346  0.123]


In [4]:
np.set_printoptions(precision=10)
print(a)

[12.3456       0.123456789]


In [5]:
np.set_printoptions(precision=4, floatmode='maxprec')
print(a)

[12.3456  0.1235]


In [6]:
np.set_printoptions(precision=10, floatmode='maxprec')
print(a)

[12.3456       0.123456789]


In [7]:
np.set_printoptions(precision=4, floatmode='fixed')
print(a)
np.set_printoptions(precision=10, floatmode='fixed')
print(a)

[12.3456  0.1235]
[12.3456000000  0.1234567890]


In [8]:
np.set_printoptions(precision=4, floatmode='maxprec_equal')
print(a)
np.set_printoptions(precision=10, floatmode='maxprec_equal')
print(a)

[12.3456  0.1235]
[12.345600000  0.123456789]


In [9]:
np.set_printoptions(precision=4, floatmode='unique')
print(a)
np.set_printoptions(precision=10, floatmode='unique')
print(a)

[12.3456       0.123456789]
[12.3456       0.123456789]


If you generate a new one,

In [10]:
b = np.round(a, 2)
print(b)

[12.35  0.12]


In [11]:
b = np.round(a, -1)
print(b)
b = np.round([1234.56, 123456.789], -2)
print(b)

[10.  0.]
[  1200. 123500.]


In [12]:
a = np.array([0.123456, 0.123456])
print(a)
a = np.array([0.123456, 0.0000123456])
print(a)
a = np.array([123.456, 0.0123456])
print(a)

[0.123456 0.123456]
[1.23456e-01 1.23456e-05]
[1.23456e+02 1.23456e-02]


In [13]:
np.set_printoptions(suppress = True)
print(a)

[123.456       0.0123456]


In [14]:
np.set_printoptions(suppress = True, precision=2)
print(a)
np.set_printoptions(suppress=False, precision=2)
print(a)
np.set_printoptions(suppress=False, precision = 8, floatmode ='fixed')
print(a)

[123.456       0.0123456]
[1.23456e+02 1.23456e-02]
[1.23456000e+02 1.23456000e-02]


formatter

In [15]:
a

array([1.23456000e+02, 1.23456000e-02])

In [16]:
np.set_printoptions(formatter = {'float': '{:.2f}'.format})
print(a)

[123.46 0.01]


In [17]:
np.set_printoptions(formatter={'float':'{:.8f}'.format})
print(a)

[123.45600000 0.01234560]


In [18]:
np.set_printoptions(formatter={'flaot': '{:.8e}'.format})
print(a)

[1.23456000e+02 1.23456000e-02]


In [19]:
a = np.array([12, 1234])
print(a)
np.set_printoptions(formatter={'int': '{:08d}'.format})
print(a)

[  12 1234]
[00000012 00001234]


In [21]:
np.set_printoptions(formatter={'int': '{:b}'.format})
print(a)

[1100 10011010010]


In [23]:
np.set_printoptions(formatter={'int':'{:x}'.format})
print(a)

[c 4d2]


In [24]:
a = np.array(['One', 'Two'])
print(a)
np.set_printoptions(formatter={'numpystr': str.upper})
print(a)

['One' 'Two']
[ONE TWO]


In [26]:
np.set_printoptions(formatter={'numpystr': lambda x: '***' + x + '***'})
print(a)

[***One*** ***Two***]


In [27]:
np.set_printoptions(formatter={'float':'{:0.8e}'.format, 'int':'{:08d}'.format})
a = np.array([12, 12.34])
print(a.dtype)
a = np.array([12,123])
print(a.dtype)

float64
int64


# threshold

In [28]:
a = np.arange(10)
print(a)

[00000000 00000001 00000002 00000003 00000004 00000005 00000006 00000007
 00000008 00000009]


In [29]:
np.set_printoptions(threshold = 10)
print(a)
np.set_printoptions(threshold=9)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 ... 7 8 9]


In [31]:
a = np.arange(100).reshape((10,10))
np.set_printoptions(threshold=100)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [33]:
np.set_printoptions(threshold = 99)
print(a)

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]


In [34]:
print(np.get_printoptions())

{'edgeitems': 3, 'threshold': 99, 'floatmode': 'fixed', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}


In [35]:
print(np.get_printoptions()['threshold'])

99


In [37]:
np.set_printoptions(threshold=0)
print(np.arange(100))
print(np.arange(7))
print(np.arange(6))

[ 0  1  2 ... 97 98 99]
[0 1 2 ... 4 5 6]
[0 1 2 3 4 5]


edgeitems : how many show numerics?

In [38]:
np.set_printoptions(edgeitems=1)
print(np.arange(6))

[0 ... 5]


In [39]:
np.set_printoptions(edgeitems=0)
print(np.arange(6))

[... 5]


In [40]:
np.set_printoptions(edgeitems=3)
print(np.arange(60).reshape((6,10)))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 [30 31 32 ... 37 38 39]
 [40 41 42 ... 47 48 49]
 [50 51 52 ... 57 58 59]]


### Dont skip it.

In [41]:
np.set_printoptions(threshold=np.inf)
print(np.arange(1001))

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

numerics, a row showing

In [42]:
np.set_printoptions(linewidth=100)
print(np.arange(1001))

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18
   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37
   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75
   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94
   95   96   97   98   99  100  101  102  103  104  105  106  107  108  109  110  111  112  113
  114  115  116  117  118  119  120  121  122  123  124  125  126  127  128  129  130  131  132
  133  134  135  136  137  138  139  140  141  142  143  144  145  146  147  148  149  150  151
  152  153  154  155  156  157  158  159  160  161  162  163  164  165  166  167  168  169  170
  171  172  173  174  175  176  177  178  179  180  181  182  183  184  185  186  187  188  189
  190  191  192  193  194  195  196  197