<a href="https://colab.research.google.com/github/anko191/Python_Kaggle/blob/master/numpy/Numpy_Initialize_and_generate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initialize

In [60]:
import numpy as np
print(np.zeros(3))
np.set_printoptions(precision=8,threshold=1000)
print(np.get_printoptions())

[0.00000000 0.00000000 0.00000000]
{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'fixed', 'precision': 8, 'suppress': False, 'linewidth': 100, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}


In [53]:
print(np.zeros((2,3)))

[[0.00000000 0.00000000 0.00000000]
 [0.00000000 0.00000000 0.00000000]]


In [54]:
print(np.zeros(3).dtype)

float64


In [55]:
print(np.zeros(3, dtype=np.int))

[0 0 0]


In [56]:
print(np.zeros(3, dtype=np.int).dtype)

int64


Initialize 1

In [57]:
print(np.ones(3))

[1.00000000 1.00000000 1.00000000]


In [61]:
print(np.ones(3, dtype = np.int).dtype)

int64


numpy.full()

In [62]:
print(np.full(3, 100))

[100 100 100]


In [63]:
print(np.full(3, np.pi))

[3.14159265 3.14159265 3.14159265]


In [64]:
print(np.full((2,3), 100))

[[100 100 100]
 [100 100 100]]


# numpy.zeros_like()

## すでにできているものを変更する。

In [65]:
a_int = np.arange(6).reshape((2,3))
print(a_int)
a_float = np.arange(6).reshape((2,3))/10
print(a_float)

[[0 1 2]
 [3 4 5]]
[[0.00000000 0.10000000 0.20000000]
 [0.30000000 0.40000000 0.50000000]]


In [66]:
print(np.zeros_like(a_int))

[[0 0 0]
 [0 0 0]]


In [67]:
print(np.zeros_like(a_float))

[[0.00000000 0.00000000 0.00000000]
 [0.00000000 0.00000000 0.00000000]]


In [68]:
print(np.zeros_like(a_int, dtype=np.float))

[[0.00000000 0.00000000 0.00000000]
 [0.00000000 0.00000000 0.00000000]]


numpy.ones_like()

In [69]:
print(np.ones_like(a_int))
print(np.ones_like(a_float))

[[1 1 1]
 [1 1 1]]
[[1.00000000 1.00000000 1.00000000]
 [1.00000000 1.00000000 1.00000000]]


In [70]:
print(np.ones_like(a_int, dtype=np.float))

[[1.00000000 1.00000000 1.00000000]
 [1.00000000 1.00000000 1.00000000]]


numpy.full_like()

In [71]:
print(np.full_like(a_int, 100))
print(np.full_like(a_float, 1000))

[[100 100 100]
 [100 100 100]]
[[1000.00000000 1000.00000000 1000.00000000]
 [1000.00000000 1000.00000000 1000.00000000]]


casting (dtype, ???) ??? is not equal to dtype is casting to dtype automatically

In [73]:
print(np.full_like(a_int, 0.123))
print(np.full_like(a_float, 0.123))

[[0 0 0]
 [0 0 0]]
[[0.12300000 0.12300000 0.12300000]
 [0.12300000 0.12300000 0.12300000]]


but dtype designate is ok

In [74]:
print(np.full_like(a_int, 0.123, dtype=np.float))

[[0.12300000 0.12300000 0.12300000]
 [0.12300000 0.12300000 0.12300000]]


slices is great

In [75]:
a[:,:] = 0
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [76]:
a[:] = 1
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [78]:
a[:] = 0.1
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


need astype

In [79]:
a = a.astype(np.float)
a[:] = 0.1
print(a)

[[0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000
  0.10000000 0.10000000]
 [0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0.10000000 0

# numpy.empty()

In [82]:
import numpy as np
print(np.empty(3))

[3.14159265 3.14159265 3.14159265]


In [83]:
print(np.empty((2,3)))

[[0.12300000 0.12300000 0.12300000]
 [0.12300000 0.12300000 0.12300000]]


In [84]:
print(np.empty(3, dtype=np.int).dtype)

int64


In [85]:
a_int = np.arange(6).reshape((2,3))

np.empty_like() ha?

In [88]:
print(np.empty_like(a_int))

[[0 1 2]
 [3 4 5]]


In [90]:
a_float = np.arange(6).reshape((2,3)) / 10
print(a_float)

[[0.00000000 0.10000000 0.20000000]
 [0.30000000 0.40000000 0.50000000]]


In [92]:
print(np.empty_like(a_float))

[[0.00000000 0.10000000 0.20000000]
 [0.30000000 0.40000000 0.50000000]]


# random generation

In [93]:
import numpy as np
rand = np.random.rand() # 1 つの乱数
print(rand)

0.593173032034094


In [95]:
arr = np.random.rand(3) # size 3's
print(arr)

[0.66052376 0.99373429 0.47098217]


In [96]:
arr = np.random.rand(4,4) # 4x4 's matrix
print(arr)

[[0.08113966 0.56947969 0.43070750 0.58461967]
 [0.84089987 0.52241275 0.66219517 0.82271487]
 [0.58564135 0.75818714 0.33886393 0.29795932]
 [0.86976050 0.60297969 0.25361038 0.26686375]]


In [98]:
arr = np.random.rand(3,2,4) # 3 x 2 x 2
print(arr)

[[[0.34180301 0.33848091 0.64697713 0.08206917]
  [0.44527679 0.11242169 0.23153261 0.16314901]]

 [[0.22552529 0.42153804 0.70540588 0.02457184]
  [0.89206373 0.84987496 0.14430786 0.95185899]]

 [[0.45836361 0.37070971 0.18666122 0.24198949]
  [0.81436120 0.60909854 0.07204601 0.63551850]]]


# numpy.random.random_sample(): Uniform distribution  

In [99]:
rand = np.random.random_sample()
print(rand)
arr = np.random.random_sample(3)
print(arr)
arr = np.random.random_sample((4,4))
print(arr)
arr = np.random.random_sample((3,2,2))
print(arr)

0.19055410614690038
[0.63693027 0.83607073 0.14541449]
[[0.83372924 0.37023656 0.25377695 0.78413656]
 [0.17199168 0.96335046 0.29185416 0.20962940]
 [0.14142088 0.48672586 0.50702566 0.38124333]
 [0.60682634 0.50226962 0.50921786 0.74186659]]
[[[0.91563973 0.01584960]
  [0.94067106 0.50620747]]

 [[0.85931658 0.71976339]
  [0.89993802 0.34504510]]

 [[0.77735415 0.48469335]
  [0.18930651 0.70246298]]]


np.random.random(), np.random.ranf(), np.random.sample() is equal to np.random.random_sample

numpy.random.randint(): designate range

In [100]:
arr = np.random.randint(4, 10, (3,3))
print(arr)

[[5 7 6]
 [9 4 5]
 [6 7 4]]


numpy.random.randn(): average = 0, decentralization = 1

In [101]:
arr = np.random.randn(3,3)
print(arr)

[[ 0.09683818  0.98053915  0.20790092]
 [ 0.06983201 -0.03055261 -0.20467997]
 [ 0.14139594 -0.33192208 -0.64420522]]


numpy.random.norma(): Normal distribution(arbitrary mean, standard deviation)

In [102]:
arr = np.random.normal(-2, 0.5, (3,3))
print(arr)

[[-2.05786862 -2.41416112 -1.72962072]
 [-1.78173718 -1.88695919 -1.84283565]
 [-2.29860441 -2.21162445 -1.38629917]]


In [103]:
arr = np.random.binomial(10, 0.5, 10)
print(arr)

[6 6 7 4 5 5 3 7 6 6]


beta

In [104]:
arr = np.random.beta(2,2,10)
print(arr)

[0.71171117 0.83126498 0.36792534 0.38090680 0.39762350 0.39483948 0.23670483 0.49861523 0.42072554
 0.10914165]


gamma shape, scale

In [105]:
arr = np.random.gamma(5,1,10)
print(arr)

[1.88004925 5.04293335 4.15582453 6.62893832 7.31522380 1.03203490 5.99791549 4.29228974 3.66243324
 4.13259362]


カイ二乗分布

In [106]:
arr = np.random.chisquare(3, 10)
print(arr)

[2.83124575 2.35186523 2.96916590 3.72809841 0.76263132 2.41023704 5.05707902 0.62959570 1.50431406
 2.10702742]


# numpy.arange(start, stop, step)

In [107]:
print(np.arange(3))
print(np.arange(3,10))
print(np.arange(3,10,2))

[0 1 2]
[3 4 5 6 7 8 9]
[3 5 7 9]


In [108]:
print(np.arange(0.3, 1.0, 0.2))

[0.30000000 0.50000000 0.70000000 0.90000000]


In [110]:
print(np.arange(-3,3))

[-3 -2 -1  0  1  2]


In [111]:
print(np.arange(3, dtype=float))
print(np.arange(3,10,2, dtype=float))

[0.00000000 1.00000000 2.00000000]
[3.00000000 5.00000000 7.00000000 9.00000000]


# numpy.linspace()
numpy.linspace(start, stop, num)

In [112]:
print(np.linspace(0, 10, 3))
print(np.linspace(0,10,4))
print(np.linspace(0,10,5))

[ 0.00000000  5.00000000 10.00000000]
[ 0.00000000  3.33333333  6.66666667 10.00000000]
[ 0.00000000  2.50000000  5.00000000  7.50000000 10.00000000]


start > stop

In [113]:
print(np.linspace(10,0,5))

[10.00000000  7.50000000  5.00000000  2.50000000  0.00000000]


In [114]:
print(np.linspace(0,10,3, dtype=int))

[ 0  5 10]


endpoint , include stop ???????

In [115]:
print(np.linspace(0, 10, 5, endpoint = False))

[0.00000000 2.00000000 4.00000000 6.00000000 8.00000000]


get step, retstep

In [117]:
result = np.linspace(0, 10, 5, endpoint = False, retstep = True)
print(result)

(array([0.00000000, 2.00000000, 4.00000000, 6.00000000, 8.00000000]), 2.0)


reversion..., [::-1] or numpy.flip()

In [118]:
print(np.arange(3,10,2)[::-1])

[9 7 5 3]


In [119]:
print(np.flip(np.arange(3,10,2)))

[9 7 5 3]


conversion Polynomial alignment

In [120]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [121]:
print(np.linspace(0,10,12).reshape(3,4))

[[ 0.00000000  0.90909091  1.81818182  2.72727273]
 [ 3.63636364  4.54545455  5.45454545  6.36363636]
 [ 7.27272727  8.18181818  9.09090909 10.00000000]]


# Make diagonal

In [122]:
a = np.arange(9).reshape((3,3))
print(a)
print(np.diag(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


quotation markers

In [123]:
print(np.diag(a, k = 1))
print(np.diag(a,k = 2))
print(np.diag(a, k = 3))

[1 5]
[2]
[]


but 3-dimension over cant use diag

# 単位行列(unit matrix)
numpy.identity()

In [124]:
print(np.diag([1,1,1]))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [126]:
print(np.identity(3, int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [127]:
a = np.arange(9).reshape((3,3))
print(a)
print(a.diagonal())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


In [128]:
print(a.diagonal(offset = 1))

[1 5]


In [129]:
a = np.arange(12).reshape((3,4))
print(a)
print(a.diagonal(offset = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1  6 11]
